/*
 * These source files contain a hardware description of a network
 * automatically generated by CONNECT (CONfigurable NEtwork Creation Tool).
 *
 * This product includes a hardware design developed by Carnegie Mellon
 * University.
 *
 * Copyright (c) 2012 by Michael K. Papamichael, Carnegie Mellon University
 *
 * For more information, see the CONNECT project website at:
 *   http://www.ece.cmu.edu/~mpapamic/connect
 *
 * This design is provided for internal, non-commercial research use only, 
 * cannot be used for, or in support of, goods or services, and is not for
 * redistribution, with or without modifications.
 * 
 * You may not use the name "Carnegie Mellon University" or derivations
 * thereof to endorse or promote products derived from this software.
 *
 * THE SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER
 * EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO ANY WARRANTY
 * THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS OR BE ERROR-FREE AND ANY
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
 * TITLE, OR NON-INFRINGEMENT.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
 * BE LIABLE FOR ANY DAMAGES, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT,
 * SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM, OR IN
 * ANY WAY CONNECTED WITH THIS SOFTWARE (WHETHER OR NOT BASED UPON WARRANTY,
 * CONTRACT, TORT OR OTHERWISE).
 *
 */


//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Sun Jun 10 13:12:32 EDT 2018
//
// Method conflict info:
// Method: output_arbs_0_select
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_1_select,
// 	       output_arbs_1_next,
// 	       output_arbs_2_select,
// 	       output_arbs_2_next,
// 	       output_arbs_3_select,
// 	       output_arbs_3_next
// Sequenced before: output_arbs_0_next
//
// Method: output_arbs_0_next
// Conflict-free: output_arbs_1_select,
// 	       output_arbs_1_next,
// 	       output_arbs_2_select,
// 	       output_arbs_2_next,
// 	       output_arbs_3_select,
// 	       output_arbs_3_next
// Sequenced after: output_arbs_0_select
// Conflicts: output_arbs_0_next
//
// Method: output_arbs_1_select
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_0_next,
// 	       output_arbs_1_select,
// 	       output_arbs_2_select,
// 	       output_arbs_2_next,
// 	       output_arbs_3_select,
// 	       output_arbs_3_next
// Sequenced before: output_arbs_1_next
//
// Method: output_arbs_1_next
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_0_next,
// 	       output_arbs_2_select,
// 	       output_arbs_2_next,
// 	       output_arbs_3_select,
// 	       output_arbs_3_next
// Sequenced after: output_arbs_1_select
// Conflicts: output_arbs_1_next
//
// Method: output_arbs_2_select
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_0_next,
// 	       output_arbs_1_select,
// 	       output_arbs_1_next,
// 	       output_arbs_2_select,
// 	       output_arbs_3_select,
// 	       output_arbs_3_next
// Sequenced before: output_arbs_2_next
//
// Method: output_arbs_2_next
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_0_next,
// 	       output_arbs_1_select,
// 	       output_arbs_1_next,
// 	       output_arbs_3_select,
// 	       output_arbs_3_next
// Sequenced after: output_arbs_2_select
// Conflicts: output_arbs_2_next
//
// Method: output_arbs_3_select
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_0_next,
// 	       output_arbs_1_select,
// 	       output_arbs_1_next,
// 	       output_arbs_2_select,
// 	       output_arbs_2_next,
// 	       output_arbs_3_select
// Sequenced before: output_arbs_3_next
//
// Method: output_arbs_3_next
// Conflict-free: output_arbs_0_select,
// 	       output_arbs_0_next,
// 	       output_arbs_1_select,
// 	       output_arbs_1_next,
// 	       output_arbs_2_select,
// 	       output_arbs_2_next
// Sequenced after: output_arbs_3_select
// Conflicts: output_arbs_3_next
//
//
// Ports:
// Name                         I/O  size props
// output_arbs_0_select           O     4
// output_arbs_1_select           O     4
// output_arbs_2_select           O     4
// output_arbs_3_select           O     4
// CLK                            I     1 clock
// RST_N                          I     1 reset
// output_arbs_0_select_requests  I     4
// output_arbs_1_select_requests  I     4
// output_arbs_2_select_requests  I     4
// output_arbs_3_select_requests  I     4
// EN_output_arbs_0_next          I     1
// EN_output_arbs_1_next          I     1
// EN_output_arbs_2_next          I     1
// EN_output_arbs_3_next          I     1
//
// Combinational paths from inputs to outputs:
//   output_arbs_0_select_requests -> output_arbs_0_select
//   output_arbs_1_select_requests -> output_arbs_1_select
//   output_arbs_2_select_requests -> output_arbs_2_select
//   output_arbs_3_select_requests -> output_arbs_3_select
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkRouterOutputArbitersRoundRobin(CLK,
					RST_N,

					output_arbs_0_select_requests,
					output_arbs_0_select,

					EN_output_arbs_0_next,

					output_arbs_1_select_requests,
					output_arbs_1_select,

					EN_output_arbs_1_next,

					output_arbs_2_select_requests,
					output_arbs_2_select,

					EN_output_arbs_2_next,

					output_arbs_3_select_requests,
					output_arbs_3_select,

					EN_output_arbs_3_next);
  input  CLK;
  input  RST_N;

  // value method output_arbs_0_select
  input  [3 : 0] output_arbs_0_select_requests;
  output [3 : 0] output_arbs_0_select;

  // action method output_arbs_0_next
  input  EN_output_arbs_0_next;

  // value method output_arbs_1_select
  input  [3 : 0] output_arbs_1_select_requests;
  output [3 : 0] output_arbs_1_select;

  // action method output_arbs_1_next
  input  EN_output_arbs_1_next;

  // value method output_arbs_2_select
  input  [3 : 0] output_arbs_2_select_requests;
  output [3 : 0] output_arbs_2_select;

  // action method output_arbs_2_next
  input  EN_output_arbs_2_next;

  // value method output_arbs_3_select
  input  [3 : 0] output_arbs_3_select_requests;
  output [3 : 0] output_arbs_3_select;

  // action method output_arbs_3_next
  input  EN_output_arbs_3_next;

  // signals for module outputs
  wire [3 : 0] output_arbs_0_select,
	       output_arbs_1_select,
	       output_arbs_2_select,
	       output_arbs_3_select;

  // register oas_0_token
  reg [3 : 0] oas_0_token;
  wire [3 : 0] oas_0_token$D_IN;
  wire oas_0_token$EN;

  // register oas_1_token
  reg [3 : 0] oas_1_token;
  wire [3 : 0] oas_1_token$D_IN;
  wire oas_1_token$EN;

  // register oas_2_token
  reg [3 : 0] oas_2_token;
  wire [3 : 0] oas_2_token$D_IN;
  wire oas_2_token$EN;

  // register oas_3_token
  reg [3 : 0] oas_3_token;
  wire [3 : 0] oas_3_token$D_IN;
  wire oas_3_token$EN;

  // remaining internal signals
  wire [1 : 0] ab__h10189,
	       ab__h10559,
	       ab__h10875,
	       ab__h11142,
	       ab__h14195,
	       ab__h14210,
	       ab__h14225,
	       ab__h14240,
	       ab__h15372,
	       ab__h15742,
	       ab__h16058,
	       ab__h16325,
	       ab__h19378,
	       ab__h19393,
	       ab__h19408,
	       ab__h19423,
	       ab__h20555,
	       ab__h20925,
	       ab__h21241,
	       ab__h21508,
	       ab__h3829,
	       ab__h3844,
	       ab__h3859,
	       ab__h3874,
	       ab__h5006,
	       ab__h5376,
	       ab__h5692,
	       ab__h5959,
	       ab__h9012,
	       ab__h9027,
	       ab__h9042,
	       ab__h9057;
  wire NOT_gen_grant_carry_0_BIT_1_1_2_AND_NOT_gen_gr_ETC___d97,
       NOT_gen_grant_carry_20_BIT_1_39_44_AND_NOT_gen_ETC___d159,
       NOT_gen_grant_carry_24_BIT_1_25_36_AND_NOT_gen_ETC___d151,
       NOT_gen_grant_carry_2_BIT_1_1_6_AND_NOT_gen_gr_ETC___d51,
       NOT_gen_grant_carry_6_BIT_1_5_0_AND_NOT_gen_gr_ETC___d105,
       NOT_gen_grant_carry_6_BIT_1_7_8_AND_NOT_gen_gr_ETC___d43,
       NOT_gen_grant_carry_74_BIT_1_93_98_AND_NOT_gen_ETC___d213,
       NOT_gen_grant_carry_78_BIT_1_79_90_AND_NOT_gen_ETC___d205,
       ab_BIT_0___h10245,
       ab_BIT_0___h10347,
       ab_BIT_0___h10663,
       ab_BIT_0___h10930,
       ab_BIT_0___h14716,
       ab_BIT_0___h14823,
       ab_BIT_0___h14930,
       ab_BIT_0___h15428,
       ab_BIT_0___h15530,
       ab_BIT_0___h15846,
       ab_BIT_0___h16113,
       ab_BIT_0___h19899,
       ab_BIT_0___h20006,
       ab_BIT_0___h20113,
       ab_BIT_0___h20611,
       ab_BIT_0___h20713,
       ab_BIT_0___h21029,
       ab_BIT_0___h21296,
       ab_BIT_0___h4350,
       ab_BIT_0___h4457,
       ab_BIT_0___h4564,
       ab_BIT_0___h5062,
       ab_BIT_0___h5164,
       ab_BIT_0___h5480,
       ab_BIT_0___h5747,
       ab_BIT_0___h9533,
       ab_BIT_0___h9640,
       ab_BIT_0___h9747,
       oas_0_token_BIT_0___h4348,
       oas_0_token_BIT_1___h4455,
       oas_0_token_BIT_2___h4562,
       oas_0_token_BIT_3___h4669,
       oas_1_token_BIT_0___h9531,
       oas_1_token_BIT_1___h9638,
       oas_1_token_BIT_2___h9745,
       oas_1_token_BIT_3___h9852,
       oas_2_token_BIT_0___h14714,
       oas_2_token_BIT_1___h14821,
       oas_2_token_BIT_2___h14928,
       oas_2_token_BIT_3___h15035,
       oas_3_token_BIT_0___h19897,
       oas_3_token_BIT_1___h20004,
       oas_3_token_BIT_2___h20111,
       oas_3_token_BIT_3___h20218;

  // value method output_arbs_0_select
  assign output_arbs_0_select =
	     { ab__h3829[1] || ab__h5006[1],
	       !ab__h3829[1] && !ab__h5006[1] &&
	       (ab__h3844[1] || ab__h5376[1]),
	       NOT_gen_grant_carry_6_BIT_1_7_8_AND_NOT_gen_gr_ETC___d43,
	       !ab__h3829[1] && !ab__h5006[1] &&
	       NOT_gen_grant_carry_2_BIT_1_1_6_AND_NOT_gen_gr_ETC___d51 } ;

  // value method output_arbs_1_select
  assign output_arbs_1_select =
	     { ab__h9012[1] || ab__h10189[1],
	       !ab__h9012[1] && !ab__h10189[1] &&
	       (ab__h9027[1] || ab__h10559[1]),
	       NOT_gen_grant_carry_0_BIT_1_1_2_AND_NOT_gen_gr_ETC___d97,
	       !ab__h9012[1] && !ab__h10189[1] &&
	       NOT_gen_grant_carry_6_BIT_1_5_0_AND_NOT_gen_gr_ETC___d105 } ;

  // value method output_arbs_2_select
  assign output_arbs_2_select =
	     { ab__h14195[1] || ab__h15372[1],
	       !ab__h14195[1] && !ab__h15372[1] &&
	       (ab__h14210[1] || ab__h15742[1]),
	       NOT_gen_grant_carry_24_BIT_1_25_36_AND_NOT_gen_ETC___d151,
	       !ab__h14195[1] && !ab__h15372[1] &&
	       NOT_gen_grant_carry_20_BIT_1_39_44_AND_NOT_gen_ETC___d159 } ;

  // value method output_arbs_3_select
  assign output_arbs_3_select =
	     { ab__h19378[1] || ab__h20555[1],
	       !ab__h19378[1] && !ab__h20555[1] &&
	       (ab__h19393[1] || ab__h20925[1]),
	       NOT_gen_grant_carry_78_BIT_1_79_90_AND_NOT_gen_ETC___d205,
	       !ab__h19378[1] && !ab__h20555[1] &&
	       NOT_gen_grant_carry_74_BIT_1_93_98_AND_NOT_gen_ETC___d213 } ;

  // register oas_0_token
  assign oas_0_token$D_IN = { oas_0_token[0], oas_0_token[3:1] } ;
  assign oas_0_token$EN = EN_output_arbs_0_next ;

  // register oas_1_token
  assign oas_1_token$D_IN = { oas_1_token[0], oas_1_token[3:1] } ;
  assign oas_1_token$EN = EN_output_arbs_1_next ;

  // register oas_2_token
  assign oas_2_token$D_IN = { oas_2_token[0], oas_2_token[3:1] } ;
  assign oas_2_token$EN = EN_output_arbs_2_next ;

  // register oas_3_token
  assign oas_3_token$D_IN = { oas_3_token[0], oas_3_token[3:1] } ;
  assign oas_3_token$EN = EN_output_arbs_3_next ;

  // remaining internal signals
  module_gen_grant_carry instance_gen_grant_carry_28(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_0_select_requests[0]),
						     .gen_grant_carry_p(oas_0_token_BIT_0___h4348),
						     .gen_grant_carry(ab__h3874));
  module_gen_grant_carry instance_gen_grant_carry_1(.gen_grant_carry_c(ab_BIT_0___h4350),
						    .gen_grant_carry_r(output_arbs_0_select_requests[1]),
						    .gen_grant_carry_p(oas_0_token_BIT_1___h4455),
						    .gen_grant_carry(ab__h3859));
  module_gen_grant_carry instance_gen_grant_carry_0(.gen_grant_carry_c(ab_BIT_0___h4457),
						    .gen_grant_carry_r(output_arbs_0_select_requests[2]),
						    .gen_grant_carry_p(oas_0_token_BIT_2___h4562),
						    .gen_grant_carry(ab__h3844));
  module_gen_grant_carry instance_gen_grant_carry_2(.gen_grant_carry_c(ab_BIT_0___h4564),
						    .gen_grant_carry_r(output_arbs_0_select_requests[3]),
						    .gen_grant_carry_p(oas_0_token_BIT_3___h4669),
						    .gen_grant_carry(ab__h3829));
  module_gen_grant_carry instance_gen_grant_carry_3(.gen_grant_carry_c(ab_BIT_0___h5062),
						    .gen_grant_carry_r(output_arbs_0_select_requests[0]),
						    .gen_grant_carry_p(oas_0_token_BIT_0___h4348),
						    .gen_grant_carry(ab__h5959));
  module_gen_grant_carry instance_gen_grant_carry_4(.gen_grant_carry_c(ab_BIT_0___h5747),
						    .gen_grant_carry_r(output_arbs_0_select_requests[1]),
						    .gen_grant_carry_p(oas_0_token_BIT_1___h4455),
						    .gen_grant_carry(ab__h5692));
  module_gen_grant_carry instance_gen_grant_carry_5(.gen_grant_carry_c(ab_BIT_0___h5480),
						    .gen_grant_carry_r(output_arbs_0_select_requests[2]),
						    .gen_grant_carry_p(oas_0_token_BIT_2___h4562),
						    .gen_grant_carry(ab__h5376));
  module_gen_grant_carry instance_gen_grant_carry_6(.gen_grant_carry_c(ab_BIT_0___h5164),
						    .gen_grant_carry_r(output_arbs_0_select_requests[3]),
						    .gen_grant_carry_p(oas_0_token_BIT_3___h4669),
						    .gen_grant_carry(ab__h5006));
  module_gen_grant_carry instance_gen_grant_carry_30(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_2_select_requests[0]),
						     .gen_grant_carry_p(oas_2_token_BIT_0___h14714),
						     .gen_grant_carry(ab__h14240));
  module_gen_grant_carry instance_gen_grant_carry_14(.gen_grant_carry_c(ab_BIT_0___h14716),
						     .gen_grant_carry_r(output_arbs_2_select_requests[1]),
						     .gen_grant_carry_p(oas_2_token_BIT_1___h14821),
						     .gen_grant_carry(ab__h14225));
  module_gen_grant_carry instance_gen_grant_carry_15(.gen_grant_carry_c(ab_BIT_0___h14823),
						     .gen_grant_carry_r(output_arbs_2_select_requests[2]),
						     .gen_grant_carry_p(oas_2_token_BIT_2___h14928),
						     .gen_grant_carry(ab__h14210));
  module_gen_grant_carry instance_gen_grant_carry_16(.gen_grant_carry_c(ab_BIT_0___h14930),
						     .gen_grant_carry_r(output_arbs_2_select_requests[3]),
						     .gen_grant_carry_p(oas_2_token_BIT_3___h15035),
						     .gen_grant_carry(ab__h14195));
  module_gen_grant_carry instance_gen_grant_carry_17(.gen_grant_carry_c(ab_BIT_0___h15428),
						     .gen_grant_carry_r(output_arbs_2_select_requests[0]),
						     .gen_grant_carry_p(oas_2_token_BIT_0___h14714),
						     .gen_grant_carry(ab__h16325));
  module_gen_grant_carry instance_gen_grant_carry_18(.gen_grant_carry_c(ab_BIT_0___h16113),
						     .gen_grant_carry_r(output_arbs_2_select_requests[1]),
						     .gen_grant_carry_p(oas_2_token_BIT_1___h14821),
						     .gen_grant_carry(ab__h16058));
  module_gen_grant_carry instance_gen_grant_carry_19(.gen_grant_carry_c(ab_BIT_0___h15846),
						     .gen_grant_carry_r(output_arbs_2_select_requests[2]),
						     .gen_grant_carry_p(oas_2_token_BIT_2___h14928),
						     .gen_grant_carry(ab__h15742));
  module_gen_grant_carry instance_gen_grant_carry_20(.gen_grant_carry_c(ab_BIT_0___h15530),
						     .gen_grant_carry_r(output_arbs_2_select_requests[3]),
						     .gen_grant_carry_p(oas_2_token_BIT_3___h15035),
						     .gen_grant_carry(ab__h15372));
  module_gen_grant_carry instance_gen_grant_carry_29(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_1_select_requests[0]),
						     .gen_grant_carry_p(oas_1_token_BIT_0___h9531),
						     .gen_grant_carry(ab__h9057));
  module_gen_grant_carry instance_gen_grant_carry_7(.gen_grant_carry_c(ab_BIT_0___h9533),
						    .gen_grant_carry_r(output_arbs_1_select_requests[1]),
						    .gen_grant_carry_p(oas_1_token_BIT_1___h9638),
						    .gen_grant_carry(ab__h9042));
  module_gen_grant_carry instance_gen_grant_carry_8(.gen_grant_carry_c(ab_BIT_0___h9640),
						    .gen_grant_carry_r(output_arbs_1_select_requests[2]),
						    .gen_grant_carry_p(oas_1_token_BIT_2___h9745),
						    .gen_grant_carry(ab__h9027));
  module_gen_grant_carry instance_gen_grant_carry_9(.gen_grant_carry_c(ab_BIT_0___h9747),
						    .gen_grant_carry_r(output_arbs_1_select_requests[3]),
						    .gen_grant_carry_p(oas_1_token_BIT_3___h9852),
						    .gen_grant_carry(ab__h9012));
  module_gen_grant_carry instance_gen_grant_carry_10(.gen_grant_carry_c(ab_BIT_0___h10245),
						     .gen_grant_carry_r(output_arbs_1_select_requests[0]),
						     .gen_grant_carry_p(oas_1_token_BIT_0___h9531),
						     .gen_grant_carry(ab__h11142));
  module_gen_grant_carry instance_gen_grant_carry_11(.gen_grant_carry_c(ab_BIT_0___h10930),
						     .gen_grant_carry_r(output_arbs_1_select_requests[1]),
						     .gen_grant_carry_p(oas_1_token_BIT_1___h9638),
						     .gen_grant_carry(ab__h10875));
  module_gen_grant_carry instance_gen_grant_carry_12(.gen_grant_carry_c(ab_BIT_0___h10663),
						     .gen_grant_carry_r(output_arbs_1_select_requests[2]),
						     .gen_grant_carry_p(oas_1_token_BIT_2___h9745),
						     .gen_grant_carry(ab__h10559));
  module_gen_grant_carry instance_gen_grant_carry_13(.gen_grant_carry_c(ab_BIT_0___h10347),
						     .gen_grant_carry_r(output_arbs_1_select_requests[3]),
						     .gen_grant_carry_p(oas_1_token_BIT_3___h9852),
						     .gen_grant_carry(ab__h10189));
  module_gen_grant_carry instance_gen_grant_carry_31(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(output_arbs_3_select_requests[0]),
						     .gen_grant_carry_p(oas_3_token_BIT_0___h19897),
						     .gen_grant_carry(ab__h19423));
  module_gen_grant_carry instance_gen_grant_carry_21(.gen_grant_carry_c(ab_BIT_0___h19899),
						     .gen_grant_carry_r(output_arbs_3_select_requests[1]),
						     .gen_grant_carry_p(oas_3_token_BIT_1___h20004),
						     .gen_grant_carry(ab__h19408));
  module_gen_grant_carry instance_gen_grant_carry_22(.gen_grant_carry_c(ab_BIT_0___h20006),
						     .gen_grant_carry_r(output_arbs_3_select_requests[2]),
						     .gen_grant_carry_p(oas_3_token_BIT_2___h20111),
						     .gen_grant_carry(ab__h19393));
  module_gen_grant_carry instance_gen_grant_carry_23(.gen_grant_carry_c(ab_BIT_0___h20113),
						     .gen_grant_carry_r(output_arbs_3_select_requests[3]),
						     .gen_grant_carry_p(oas_3_token_BIT_3___h20218),
						     .gen_grant_carry(ab__h19378));
  module_gen_grant_carry instance_gen_grant_carry_24(.gen_grant_carry_c(ab_BIT_0___h20611),
						     .gen_grant_carry_r(output_arbs_3_select_requests[0]),
						     .gen_grant_carry_p(oas_3_token_BIT_0___h19897),
						     .gen_grant_carry(ab__h21508));
  module_gen_grant_carry instance_gen_grant_carry_25(.gen_grant_carry_c(ab_BIT_0___h21296),
						     .gen_grant_carry_r(output_arbs_3_select_requests[1]),
						     .gen_grant_carry_p(oas_3_token_BIT_1___h20004),
						     .gen_grant_carry(ab__h21241));
  module_gen_grant_carry instance_gen_grant_carry_26(.gen_grant_carry_c(ab_BIT_0___h21029),
						     .gen_grant_carry_r(output_arbs_3_select_requests[2]),
						     .gen_grant_carry_p(oas_3_token_BIT_2___h20111),
						     .gen_grant_carry(ab__h20925));
  module_gen_grant_carry instance_gen_grant_carry_27(.gen_grant_carry_c(ab_BIT_0___h20713),
						     .gen_grant_carry_r(output_arbs_3_select_requests[3]),
						     .gen_grant_carry_p(oas_3_token_BIT_3___h20218),
						     .gen_grant_carry(ab__h20555));
  assign NOT_gen_grant_carry_0_BIT_1_1_2_AND_NOT_gen_gr_ETC___d97 =
	     !ab__h9012[1] && !ab__h10189[1] && !ab__h9027[1] &&
	     !ab__h10559[1] &&
	     (ab__h9042[1] || ab__h10875[1]) ;
  assign NOT_gen_grant_carry_20_BIT_1_39_44_AND_NOT_gen_ETC___d159 =
	     !ab__h14210[1] && !ab__h15742[1] && !ab__h14225[1] &&
	     !ab__h16058[1] &&
	     (ab__h14240[1] || ab__h16325[1]) ;
  assign NOT_gen_grant_carry_24_BIT_1_25_36_AND_NOT_gen_ETC___d151 =
	     !ab__h14195[1] && !ab__h15372[1] && !ab__h14210[1] &&
	     !ab__h15742[1] &&
	     (ab__h14225[1] || ab__h16058[1]) ;
  assign NOT_gen_grant_carry_2_BIT_1_1_6_AND_NOT_gen_gr_ETC___d51 =
	     !ab__h3844[1] && !ab__h5376[1] && !ab__h3859[1] &&
	     !ab__h5692[1] &&
	     (ab__h3874[1] || ab__h5959[1]) ;
  assign NOT_gen_grant_carry_6_BIT_1_5_0_AND_NOT_gen_gr_ETC___d105 =
	     !ab__h9027[1] && !ab__h10559[1] && !ab__h9042[1] &&
	     !ab__h10875[1] &&
	     (ab__h9057[1] || ab__h11142[1]) ;
  assign NOT_gen_grant_carry_6_BIT_1_7_8_AND_NOT_gen_gr_ETC___d43 =
	     !ab__h3829[1] && !ab__h5006[1] && !ab__h3844[1] &&
	     !ab__h5376[1] &&
	     (ab__h3859[1] || ab__h5692[1]) ;
  assign NOT_gen_grant_carry_74_BIT_1_93_98_AND_NOT_gen_ETC___d213 =
	     !ab__h19393[1] && !ab__h20925[1] && !ab__h19408[1] &&
	     !ab__h21241[1] &&
	     (ab__h19423[1] || ab__h21508[1]) ;
  assign NOT_gen_grant_carry_78_BIT_1_79_90_AND_NOT_gen_ETC___d205 =
	     !ab__h19378[1] && !ab__h20555[1] && !ab__h19393[1] &&
	     !ab__h20925[1] &&
	     (ab__h19408[1] || ab__h21241[1]) ;
  assign ab_BIT_0___h10245 = ab__h9012[0] ;
  assign ab_BIT_0___h10347 = ab__h10559[0] ;
  assign ab_BIT_0___h10663 = ab__h10875[0] ;
  assign ab_BIT_0___h10930 = ab__h11142[0] ;
  assign ab_BIT_0___h14716 = ab__h14240[0] ;
  assign ab_BIT_0___h14823 = ab__h14225[0] ;
  assign ab_BIT_0___h14930 = ab__h14210[0] ;
  assign ab_BIT_0___h15428 = ab__h14195[0] ;
  assign ab_BIT_0___h15530 = ab__h15742[0] ;
  assign ab_BIT_0___h15846 = ab__h16058[0] ;
  assign ab_BIT_0___h16113 = ab__h16325[0] ;
  assign ab_BIT_0___h19899 = ab__h19423[0] ;
  assign ab_BIT_0___h20006 = ab__h19408[0] ;
  assign ab_BIT_0___h20113 = ab__h19393[0] ;
  assign ab_BIT_0___h20611 = ab__h19378[0] ;
  assign ab_BIT_0___h20713 = ab__h20925[0] ;
  assign ab_BIT_0___h21029 = ab__h21241[0] ;
  assign ab_BIT_0___h21296 = ab__h21508[0] ;
  assign ab_BIT_0___h4350 = ab__h3874[0] ;
  assign ab_BIT_0___h4457 = ab__h3859[0] ;
  assign ab_BIT_0___h4564 = ab__h3844[0] ;
  assign ab_BIT_0___h5062 = ab__h3829[0] ;
  assign ab_BIT_0___h5164 = ab__h5376[0] ;
  assign ab_BIT_0___h5480 = ab__h5692[0] ;
  assign ab_BIT_0___h5747 = ab__h5959[0] ;
  assign ab_BIT_0___h9533 = ab__h9057[0] ;
  assign ab_BIT_0___h9640 = ab__h9042[0] ;
  assign ab_BIT_0___h9747 = ab__h9027[0] ;
  assign oas_0_token_BIT_0___h4348 = oas_0_token[0] ;
  assign oas_0_token_BIT_1___h4455 = oas_0_token[1] ;
  assign oas_0_token_BIT_2___h4562 = oas_0_token[2] ;
  assign oas_0_token_BIT_3___h4669 = oas_0_token[3] ;
  assign oas_1_token_BIT_0___h9531 = oas_1_token[0] ;
  assign oas_1_token_BIT_1___h9638 = oas_1_token[1] ;
  assign oas_1_token_BIT_2___h9745 = oas_1_token[2] ;
  assign oas_1_token_BIT_3___h9852 = oas_1_token[3] ;
  assign oas_2_token_BIT_0___h14714 = oas_2_token[0] ;
  assign oas_2_token_BIT_1___h14821 = oas_2_token[1] ;
  assign oas_2_token_BIT_2___h14928 = oas_2_token[2] ;
  assign oas_2_token_BIT_3___h15035 = oas_2_token[3] ;
  assign oas_3_token_BIT_0___h19897 = oas_3_token[0] ;
  assign oas_3_token_BIT_1___h20004 = oas_3_token[1] ;
  assign oas_3_token_BIT_2___h20111 = oas_3_token[2] ;
  assign oas_3_token_BIT_3___h20218 = oas_3_token[3] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (!RST_N)
      begin
        oas_0_token <= `BSV_ASSIGNMENT_DELAY 4'd1;
	oas_1_token <= `BSV_ASSIGNMENT_DELAY 4'd2;
	oas_2_token <= `BSV_ASSIGNMENT_DELAY 4'd4;
	oas_3_token <= `BSV_ASSIGNMENT_DELAY 4'd8;
      end
    else
      begin
        if (oas_0_token$EN)
	  oas_0_token <= `BSV_ASSIGNMENT_DELAY oas_0_token$D_IN;
	if (oas_1_token$EN)
	  oas_1_token <= `BSV_ASSIGNMENT_DELAY oas_1_token$D_IN;
	if (oas_2_token$EN)
	  oas_2_token <= `BSV_ASSIGNMENT_DELAY oas_2_token$D_IN;
	if (oas_3_token$EN)
	  oas_3_token <= `BSV_ASSIGNMENT_DELAY oas_3_token$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    oas_0_token = 4'hA;
    oas_1_token = 4'hA;
    oas_2_token = 4'hA;
    oas_3_token = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkRouterOutputArbitersRoundRobin

