webtalk_init -webtalk_dir /home/vipin/workspace/Research/mygit/OpenNoc/Imp/Vivado/openNoc.sim/sim_1/behav/xsim/xsim.dir/Test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 27 16:38:20 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "72e165c2-e2f4-4a22-9943-c665405a7761" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0a08c6ceaa914cae91a2341ac849d7d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3299.688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "594268 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "73.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "137264_KB" -context "xsim\\usage"
webtalk_transmit -clientid 307915857 -regid "" -xml /home/vipin/workspace/Research/mygit/OpenNoc/Imp/Vivado/openNoc.sim/sim_1/behav/xsim/xsim.dir/Test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/vipin/workspace/Research/mygit/OpenNoc/Imp/Vivado/openNoc.sim/sim_1/behav/xsim/xsim.dir/Test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/vipin/workspace/Research/mygit/OpenNoc/Imp/Vivado/openNoc.sim/sim_1/behav/xsim/xsim.dir/Test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
