/*
 * These source files contain a hardware description of a network
 * automatically generated by CONNECT (CONfigurable NEtwork Creation Tool).
 *
 * This product includes a hardware design developed by Carnegie Mellon
 * University.
 *
 * Copyright (c) 2012 by Michael K. Papamichael, Carnegie Mellon University
 *
 * For more information, see the CONNECT project website at:
 *   http://www.ece.cmu.edu/~mpapamic/connect
 *
 * This design is provided for internal, non-commercial research use only, 
 * cannot be used for, or in support of, goods or services, and is not for
 * redistribution, with or without modifications.
 * 
 * You may not use the name "Carnegie Mellon University" or derivations
 * thereof to endorse or promote products derived from this software.
 *
 * THE SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER
 * EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO ANY WARRANTY
 * THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS OR BE ERROR-FREE AND ANY
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
 * TITLE, OR NON-INFRINGEMENT.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
 * BE LIABLE FOR ANY DAMAGES, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT,
 * SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM, OR IN
 * ANY WAY CONNECTED WITH THIS SOFTWARE (WHETHER OR NOT BASED UPON WARRANTY,
 * CONTRACT, TORT OR OTHERWISE).
 *
 */


//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Sun Jun 10 13:00:57 EDT 2018
//
// Method conflict info:
// Method: send_ports_0_putFlit
// Conflict-free: send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Conflicts: send_ports_0_putFlit
//
// Method: send_ports_0_getNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: send_ports_1_putFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Conflicts: send_ports_1_putFlit
//
// Method: send_ports_1_getNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: send_ports_2_putFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Conflicts: send_ports_2_putFlit
//
// Method: send_ports_2_getNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: send_ports_3_putFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Conflicts: send_ports_3_putFlit
//
// Method: send_ports_3_getNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: recv_ports_0_getFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced after (restricted): recv_ports_0_putNonFullVCs
//
// Method: recv_ports_0_putNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced before (restricted): recv_ports_0_getFlit
// Conflicts: recv_ports_0_putNonFullVCs
//
// Method: recv_ports_1_getFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced after (restricted): recv_ports_1_putNonFullVCs
//
// Method: recv_ports_1_putNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced before (restricted): recv_ports_1_getFlit
// Conflicts: recv_ports_1_putNonFullVCs
//
// Method: recv_ports_2_getFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced after (restricted): recv_ports_2_putNonFullVCs
//
// Method: recv_ports_2_putNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced before (restricted): recv_ports_2_getFlit
// Conflicts: recv_ports_2_putNonFullVCs
//
// Method: recv_ports_3_getFlit
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced after (restricted): recv_ports_3_putNonFullVCs
//
// Method: recv_ports_3_putNonFullVCs
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
// Sequenced before (restricted): recv_ports_3_getFlit
// Conflicts: recv_ports_3_putNonFullVCs
//
// Method: recv_ports_info_0_getRecvPortID
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: recv_ports_info_1_getRecvPortID
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: recv_ports_info_2_getRecvPortID
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
// Method: recv_ports_info_3_getRecvPortID
// Conflict-free: send_ports_0_putFlit,
// 	       send_ports_0_getNonFullVCs,
// 	       send_ports_1_putFlit,
// 	       send_ports_1_getNonFullVCs,
// 	       send_ports_2_putFlit,
// 	       send_ports_2_getNonFullVCs,
// 	       send_ports_3_putFlit,
// 	       send_ports_3_getNonFullVCs,
// 	       recv_ports_0_getFlit,
// 	       recv_ports_0_putNonFullVCs,
// 	       recv_ports_1_getFlit,
// 	       recv_ports_1_putNonFullVCs,
// 	       recv_ports_2_getFlit,
// 	       recv_ports_2_putNonFullVCs,
// 	       recv_ports_3_getFlit,
// 	       recv_ports_3_putNonFullVCs,
// 	       recv_ports_info_0_getRecvPortID,
// 	       recv_ports_info_1_getRecvPortID,
// 	       recv_ports_info_2_getRecvPortID,
// 	       recv_ports_info_3_getRecvPortID
//
//
// Ports:
// Name                         I/O  size props
// send_ports_0_getNonFullVCs     O     2
// send_ports_1_getNonFullVCs     O     2
// send_ports_2_getNonFullVCs     O     2
// send_ports_3_getNonFullVCs     O     2
// recv_ports_0_getFlit           O    37
// recv_ports_1_getFlit           O    37
// recv_ports_2_getFlit           O    37
// recv_ports_3_getFlit           O    37
// recv_ports_info_0_getRecvPortID  O     2 const
// recv_ports_info_1_getRecvPortID  O     2 const
// recv_ports_info_2_getRecvPortID  O     2 const
// recv_ports_info_3_getRecvPortID  O     2 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// send_ports_0_putFlit_flit_in   I    37
// send_ports_1_putFlit_flit_in   I    37
// send_ports_2_putFlit_flit_in   I    37
// send_ports_3_putFlit_flit_in   I    37
// recv_ports_0_putNonFullVCs_nonFullVCs  I     2
// recv_ports_1_putNonFullVCs_nonFullVCs  I     2
// recv_ports_2_putNonFullVCs_nonFullVCs  I     2
// recv_ports_3_putNonFullVCs_nonFullVCs  I     2
// EN_send_ports_0_putFlit        I     1
// EN_send_ports_1_putFlit        I     1
// EN_send_ports_2_putFlit        I     1
// EN_send_ports_3_putFlit        I     1
// EN_recv_ports_0_putNonFullVCs  I     1
// EN_recv_ports_1_putNonFullVCs  I     1
// EN_recv_ports_2_putNonFullVCs  I     1
// EN_recv_ports_3_putNonFullVCs  I     1
// EN_send_ports_0_getNonFullVCs  I     1 unused
// EN_send_ports_1_getNonFullVCs  I     1 unused
// EN_send_ports_2_getNonFullVCs  I     1 unused
// EN_send_ports_3_getNonFullVCs  I     1 unused
// EN_recv_ports_0_getFlit        I     1 unused
// EN_recv_ports_1_getFlit        I     1 unused
// EN_recv_ports_2_getFlit        I     1 unused
// EN_recv_ports_3_getFlit        I     1 unused
//
// Combinational paths from inputs to outputs:
//   (recv_ports_0_putNonFullVCs_nonFullVCs,
//    EN_recv_ports_0_putNonFullVCs) -> recv_ports_0_getFlit
//   (recv_ports_1_putNonFullVCs_nonFullVCs,
//    EN_recv_ports_1_putNonFullVCs) -> recv_ports_1_getFlit
//   (recv_ports_2_putNonFullVCs_nonFullVCs,
//    EN_recv_ports_2_putNonFullVCs) -> recv_ports_2_getFlit
//   (recv_ports_3_putNonFullVCs_nonFullVCs,
//    EN_recv_ports_3_putNonFullVCs) -> recv_ports_3_getFlit
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkNetworkSimple(CLK,
		       RST_N,

		       send_ports_0_putFlit_flit_in,
		       EN_send_ports_0_putFlit,

		       EN_send_ports_0_getNonFullVCs,
		       send_ports_0_getNonFullVCs,

		       send_ports_1_putFlit_flit_in,
		       EN_send_ports_1_putFlit,

		       EN_send_ports_1_getNonFullVCs,
		       send_ports_1_getNonFullVCs,

		       send_ports_2_putFlit_flit_in,
		       EN_send_ports_2_putFlit,

		       EN_send_ports_2_getNonFullVCs,
		       send_ports_2_getNonFullVCs,

		       send_ports_3_putFlit_flit_in,
		       EN_send_ports_3_putFlit,

		       EN_send_ports_3_getNonFullVCs,
		       send_ports_3_getNonFullVCs,

		       EN_recv_ports_0_getFlit,
		       recv_ports_0_getFlit,

		       recv_ports_0_putNonFullVCs_nonFullVCs,
		       EN_recv_ports_0_putNonFullVCs,

		       EN_recv_ports_1_getFlit,
		       recv_ports_1_getFlit,

		       recv_ports_1_putNonFullVCs_nonFullVCs,
		       EN_recv_ports_1_putNonFullVCs,

		       EN_recv_ports_2_getFlit,
		       recv_ports_2_getFlit,

		       recv_ports_2_putNonFullVCs_nonFullVCs,
		       EN_recv_ports_2_putNonFullVCs,

		       EN_recv_ports_3_getFlit,
		       recv_ports_3_getFlit,

		       recv_ports_3_putNonFullVCs_nonFullVCs,
		       EN_recv_ports_3_putNonFullVCs,

		       recv_ports_info_0_getRecvPortID,

		       recv_ports_info_1_getRecvPortID,

		       recv_ports_info_2_getRecvPortID,

		       recv_ports_info_3_getRecvPortID);
  input  CLK;
  input  RST_N;

  // action method send_ports_0_putFlit
  input  [36 : 0] send_ports_0_putFlit_flit_in;
  input  EN_send_ports_0_putFlit;

  // actionvalue method send_ports_0_getNonFullVCs
  input  EN_send_ports_0_getNonFullVCs;
  output [1 : 0] send_ports_0_getNonFullVCs;

  // action method send_ports_1_putFlit
  input  [36 : 0] send_ports_1_putFlit_flit_in;
  input  EN_send_ports_1_putFlit;

  // actionvalue method send_ports_1_getNonFullVCs
  input  EN_send_ports_1_getNonFullVCs;
  output [1 : 0] send_ports_1_getNonFullVCs;

  // action method send_ports_2_putFlit
  input  [36 : 0] send_ports_2_putFlit_flit_in;
  input  EN_send_ports_2_putFlit;

  // actionvalue method send_ports_2_getNonFullVCs
  input  EN_send_ports_2_getNonFullVCs;
  output [1 : 0] send_ports_2_getNonFullVCs;

  // action method send_ports_3_putFlit
  input  [36 : 0] send_ports_3_putFlit_flit_in;
  input  EN_send_ports_3_putFlit;

  // actionvalue method send_ports_3_getNonFullVCs
  input  EN_send_ports_3_getNonFullVCs;
  output [1 : 0] send_ports_3_getNonFullVCs;

  // actionvalue method recv_ports_0_getFlit
  input  EN_recv_ports_0_getFlit;
  output [36 : 0] recv_ports_0_getFlit;

  // action method recv_ports_0_putNonFullVCs
  input  [1 : 0] recv_ports_0_putNonFullVCs_nonFullVCs;
  input  EN_recv_ports_0_putNonFullVCs;

  // actionvalue method recv_ports_1_getFlit
  input  EN_recv_ports_1_getFlit;
  output [36 : 0] recv_ports_1_getFlit;

  // action method recv_ports_1_putNonFullVCs
  input  [1 : 0] recv_ports_1_putNonFullVCs_nonFullVCs;
  input  EN_recv_ports_1_putNonFullVCs;

  // actionvalue method recv_ports_2_getFlit
  input  EN_recv_ports_2_getFlit;
  output [36 : 0] recv_ports_2_getFlit;

  // action method recv_ports_2_putNonFullVCs
  input  [1 : 0] recv_ports_2_putNonFullVCs_nonFullVCs;
  input  EN_recv_ports_2_putNonFullVCs;

  // actionvalue method recv_ports_3_getFlit
  input  EN_recv_ports_3_getFlit;
  output [36 : 0] recv_ports_3_getFlit;

  // action method recv_ports_3_putNonFullVCs
  input  [1 : 0] recv_ports_3_putNonFullVCs_nonFullVCs;
  input  EN_recv_ports_3_putNonFullVCs;

  // value method recv_ports_info_0_getRecvPortID
  output [1 : 0] recv_ports_info_0_getRecvPortID;

  // value method recv_ports_info_1_getRecvPortID
  output [1 : 0] recv_ports_info_1_getRecvPortID;

  // value method recv_ports_info_2_getRecvPortID
  output [1 : 0] recv_ports_info_2_getRecvPortID;

  // value method recv_ports_info_3_getRecvPortID
  output [1 : 0] recv_ports_info_3_getRecvPortID;

  // signals for module outputs
  wire [36 : 0] recv_ports_0_getFlit,
		recv_ports_1_getFlit,
		recv_ports_2_getFlit,
		recv_ports_3_getFlit;
  wire [1 : 0] recv_ports_info_0_getRecvPortID,
	       recv_ports_info_1_getRecvPortID,
	       recv_ports_info_2_getRecvPortID,
	       recv_ports_info_3_getRecvPortID,
	       send_ports_0_getNonFullVCs,
	       send_ports_1_getNonFullVCs,
	       send_ports_2_getNonFullVCs,
	       send_ports_3_getNonFullVCs;

  // ports of submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf
  wire [2 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf$D_IN,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf$ADDR_1,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf$ADDR_IN;
  wire net_routers_routeTable_1_rt_ifc_banks_banks_rf$WE;

  // ports of submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_1
  wire [2 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$D_IN;
  wire [1 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$ADDR_1,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$ADDR_IN;
  wire net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$WE;

  // ports of submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_2
  wire [2 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$D_IN,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$ADDR_1,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$ADDR_IN;
  wire net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$WE;

  // ports of submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_3
  wire [2 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$D_IN,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$ADDR_1,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$ADDR_IN;
  wire net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$WE;

  // ports of submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_4
  wire [2 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$D_IN;
  wire [1 : 0] net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$ADDR_1,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$ADDR_IN;
  wire net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$WE;

  // ports of submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf
  wire [2 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf$D_IN,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf$ADDR_1,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf$ADDR_IN;
  wire net_routers_routeTable_2_rt_ifc_banks_banks_rf$WE;

  // ports of submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_1
  wire [2 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$D_IN,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$ADDR_1,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$ADDR_IN;
  wire net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$WE;

  // ports of submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_2
  wire [2 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$D_IN;
  wire [1 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$ADDR_1,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$ADDR_IN;
  wire net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$WE;

  // ports of submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_3
  wire [2 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$D_IN;
  wire [1 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$ADDR_1,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$ADDR_IN;
  wire net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$WE;

  // ports of submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_4
  wire [2 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$D_IN,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$ADDR_1,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$ADDR_IN;
  wire net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$WE;

  // ports of submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf
  wire [2 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf$D_IN,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf$ADDR_1,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf$ADDR_IN;
  wire net_routers_routeTable_3_rt_ifc_banks_banks_rf$WE;

  // ports of submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_1
  wire [2 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$D_IN;
  wire [1 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$ADDR_1,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$ADDR_IN;
  wire net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$WE;

  // ports of submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_2
  wire [2 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$D_IN;
  wire [1 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$ADDR_1,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$ADDR_IN;
  wire net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$WE;

  // ports of submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_3
  wire [2 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$D_IN,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$ADDR_1,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$ADDR_IN;
  wire net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$WE;

  // ports of submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_4
  wire [2 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$D_IN,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$ADDR_1,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$ADDR_IN;
  wire net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$WE;

  // ports of submodule net_routers_routeTable_rt_ifc_banks_banks_rf
  wire [2 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf$D_IN,
	       net_routers_routeTable_rt_ifc_banks_banks_rf$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf$ADDR_1,
	       net_routers_routeTable_rt_ifc_banks_banks_rf$ADDR_IN;
  wire net_routers_routeTable_rt_ifc_banks_banks_rf$WE;

  // ports of submodule net_routers_routeTable_rt_ifc_banks_banks_rf_1
  wire [2 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_1$D_IN,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_1$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_1$ADDR_1,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_1$ADDR_IN;
  wire net_routers_routeTable_rt_ifc_banks_banks_rf_1$WE;

  // ports of submodule net_routers_routeTable_rt_ifc_banks_banks_rf_2
  wire [2 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_2$D_IN,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_2$D_OUT_1;
  wire [1 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_2$ADDR_1,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_2$ADDR_IN;
  wire net_routers_routeTable_rt_ifc_banks_banks_rf_2$WE;

  // ports of submodule net_routers_routeTable_rt_ifc_banks_banks_rf_3
  wire [2 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_3$D_IN;
  wire [1 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_3$ADDR_1,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_3$ADDR_IN;
  wire net_routers_routeTable_rt_ifc_banks_banks_rf_3$WE;

  // ports of submodule net_routers_routeTable_rt_ifc_banks_banks_rf_4
  wire [2 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_4$D_IN;
  wire [1 : 0] net_routers_routeTable_rt_ifc_banks_banks_rf_4$ADDR_1,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_4$ADDR_IN;
  wire net_routers_routeTable_rt_ifc_banks_banks_rf_4$WE;

  // ports of submodule net_routers_router_core
  wire [39 : 0] net_routers_router_core$in_ports_0_putRoutedFlit_flit_in,
		net_routers_router_core$in_ports_1_putRoutedFlit_flit_in,
		net_routers_router_core$in_ports_2_putRoutedFlit_flit_in,
		net_routers_router_core$in_ports_3_putRoutedFlit_flit_in,
		net_routers_router_core$in_ports_4_putRoutedFlit_flit_in;
  wire [36 : 0] net_routers_router_core$out_ports_0_getFlit,
		net_routers_router_core$out_ports_3_getFlit,
		net_routers_router_core$out_ports_4_getFlit;
  wire [1 : 0] net_routers_router_core$in_ports_0_getNonFullVCs,
	       net_routers_router_core$in_ports_1_getNonFullVCs,
	       net_routers_router_core$in_ports_2_getNonFullVCs,
	       net_routers_router_core$out_ports_0_putNonFullVCs_nonFullVCs,
	       net_routers_router_core$out_ports_1_putNonFullVCs_nonFullVCs,
	       net_routers_router_core$out_ports_2_putNonFullVCs_nonFullVCs,
	       net_routers_router_core$out_ports_3_putNonFullVCs_nonFullVCs,
	       net_routers_router_core$out_ports_4_putNonFullVCs_nonFullVCs;
  wire net_routers_router_core$EN_in_ports_0_getNonFullVCs,
       net_routers_router_core$EN_in_ports_0_putRoutedFlit,
       net_routers_router_core$EN_in_ports_1_getNonFullVCs,
       net_routers_router_core$EN_in_ports_1_putRoutedFlit,
       net_routers_router_core$EN_in_ports_2_getNonFullVCs,
       net_routers_router_core$EN_in_ports_2_putRoutedFlit,
       net_routers_router_core$EN_in_ports_3_getNonFullVCs,
       net_routers_router_core$EN_in_ports_3_putRoutedFlit,
       net_routers_router_core$EN_in_ports_4_getNonFullVCs,
       net_routers_router_core$EN_in_ports_4_putRoutedFlit,
       net_routers_router_core$EN_out_ports_0_getFlit,
       net_routers_router_core$EN_out_ports_0_putNonFullVCs,
       net_routers_router_core$EN_out_ports_1_getFlit,
       net_routers_router_core$EN_out_ports_1_putNonFullVCs,
       net_routers_router_core$EN_out_ports_2_getFlit,
       net_routers_router_core$EN_out_ports_2_putNonFullVCs,
       net_routers_router_core$EN_out_ports_3_getFlit,
       net_routers_router_core$EN_out_ports_3_putNonFullVCs,
       net_routers_router_core$EN_out_ports_4_getFlit,
       net_routers_router_core$EN_out_ports_4_putNonFullVCs;

  // ports of submodule net_routers_router_core_1
  wire [39 : 0] net_routers_router_core_1$in_ports_0_putRoutedFlit_flit_in,
		net_routers_router_core_1$in_ports_1_putRoutedFlit_flit_in,
		net_routers_router_core_1$in_ports_2_putRoutedFlit_flit_in,
		net_routers_router_core_1$in_ports_3_putRoutedFlit_flit_in,
		net_routers_router_core_1$in_ports_4_putRoutedFlit_flit_in;
  wire [36 : 0] net_routers_router_core_1$out_ports_0_getFlit,
		net_routers_router_core_1$out_ports_1_getFlit,
		net_routers_router_core_1$out_ports_4_getFlit;
  wire [1 : 0] net_routers_router_core_1$in_ports_0_getNonFullVCs,
	       net_routers_router_core_1$in_ports_2_getNonFullVCs,
	       net_routers_router_core_1$in_ports_3_getNonFullVCs,
	       net_routers_router_core_1$out_ports_0_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_1$out_ports_1_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_1$out_ports_2_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_1$out_ports_3_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_1$out_ports_4_putNonFullVCs_nonFullVCs;
  wire net_routers_router_core_1$EN_in_ports_0_getNonFullVCs,
       net_routers_router_core_1$EN_in_ports_0_putRoutedFlit,
       net_routers_router_core_1$EN_in_ports_1_getNonFullVCs,
       net_routers_router_core_1$EN_in_ports_1_putRoutedFlit,
       net_routers_router_core_1$EN_in_ports_2_getNonFullVCs,
       net_routers_router_core_1$EN_in_ports_2_putRoutedFlit,
       net_routers_router_core_1$EN_in_ports_3_getNonFullVCs,
       net_routers_router_core_1$EN_in_ports_3_putRoutedFlit,
       net_routers_router_core_1$EN_in_ports_4_getNonFullVCs,
       net_routers_router_core_1$EN_in_ports_4_putRoutedFlit,
       net_routers_router_core_1$EN_out_ports_0_getFlit,
       net_routers_router_core_1$EN_out_ports_0_putNonFullVCs,
       net_routers_router_core_1$EN_out_ports_1_getFlit,
       net_routers_router_core_1$EN_out_ports_1_putNonFullVCs,
       net_routers_router_core_1$EN_out_ports_2_getFlit,
       net_routers_router_core_1$EN_out_ports_2_putNonFullVCs,
       net_routers_router_core_1$EN_out_ports_3_getFlit,
       net_routers_router_core_1$EN_out_ports_3_putNonFullVCs,
       net_routers_router_core_1$EN_out_ports_4_getFlit,
       net_routers_router_core_1$EN_out_ports_4_putNonFullVCs;

  // ports of submodule net_routers_router_core_2
  wire [39 : 0] net_routers_router_core_2$in_ports_0_putRoutedFlit_flit_in,
		net_routers_router_core_2$in_ports_1_putRoutedFlit_flit_in,
		net_routers_router_core_2$in_ports_2_putRoutedFlit_flit_in,
		net_routers_router_core_2$in_ports_3_putRoutedFlit_flit_in,
		net_routers_router_core_2$in_ports_4_putRoutedFlit_flit_in;
  wire [36 : 0] net_routers_router_core_2$out_ports_0_getFlit,
		net_routers_router_core_2$out_ports_2_getFlit,
		net_routers_router_core_2$out_ports_3_getFlit;
  wire [1 : 0] net_routers_router_core_2$in_ports_0_getNonFullVCs,
	       net_routers_router_core_2$in_ports_1_getNonFullVCs,
	       net_routers_router_core_2$in_ports_4_getNonFullVCs,
	       net_routers_router_core_2$out_ports_0_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_2$out_ports_1_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_2$out_ports_2_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_2$out_ports_3_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_2$out_ports_4_putNonFullVCs_nonFullVCs;
  wire net_routers_router_core_2$EN_in_ports_0_getNonFullVCs,
       net_routers_router_core_2$EN_in_ports_0_putRoutedFlit,
       net_routers_router_core_2$EN_in_ports_1_getNonFullVCs,
       net_routers_router_core_2$EN_in_ports_1_putRoutedFlit,
       net_routers_router_core_2$EN_in_ports_2_getNonFullVCs,
       net_routers_router_core_2$EN_in_ports_2_putRoutedFlit,
       net_routers_router_core_2$EN_in_ports_3_getNonFullVCs,
       net_routers_router_core_2$EN_in_ports_3_putRoutedFlit,
       net_routers_router_core_2$EN_in_ports_4_getNonFullVCs,
       net_routers_router_core_2$EN_in_ports_4_putRoutedFlit,
       net_routers_router_core_2$EN_out_ports_0_getFlit,
       net_routers_router_core_2$EN_out_ports_0_putNonFullVCs,
       net_routers_router_core_2$EN_out_ports_1_getFlit,
       net_routers_router_core_2$EN_out_ports_1_putNonFullVCs,
       net_routers_router_core_2$EN_out_ports_2_getFlit,
       net_routers_router_core_2$EN_out_ports_2_putNonFullVCs,
       net_routers_router_core_2$EN_out_ports_3_getFlit,
       net_routers_router_core_2$EN_out_ports_3_putNonFullVCs,
       net_routers_router_core_2$EN_out_ports_4_getFlit,
       net_routers_router_core_2$EN_out_ports_4_putNonFullVCs;

  // ports of submodule net_routers_router_core_3
  wire [39 : 0] net_routers_router_core_3$in_ports_0_putRoutedFlit_flit_in,
		net_routers_router_core_3$in_ports_1_putRoutedFlit_flit_in,
		net_routers_router_core_3$in_ports_2_putRoutedFlit_flit_in,
		net_routers_router_core_3$in_ports_3_putRoutedFlit_flit_in,
		net_routers_router_core_3$in_ports_4_putRoutedFlit_flit_in;
  wire [36 : 0] net_routers_router_core_3$out_ports_0_getFlit,
		net_routers_router_core_3$out_ports_1_getFlit,
		net_routers_router_core_3$out_ports_2_getFlit;
  wire [1 : 0] net_routers_router_core_3$in_ports_0_getNonFullVCs,
	       net_routers_router_core_3$in_ports_3_getNonFullVCs,
	       net_routers_router_core_3$in_ports_4_getNonFullVCs,
	       net_routers_router_core_3$out_ports_0_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_3$out_ports_1_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_3$out_ports_2_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_3$out_ports_3_putNonFullVCs_nonFullVCs,
	       net_routers_router_core_3$out_ports_4_putNonFullVCs_nonFullVCs;
  wire net_routers_router_core_3$EN_in_ports_0_getNonFullVCs,
       net_routers_router_core_3$EN_in_ports_0_putRoutedFlit,
       net_routers_router_core_3$EN_in_ports_1_getNonFullVCs,
       net_routers_router_core_3$EN_in_ports_1_putRoutedFlit,
       net_routers_router_core_3$EN_in_ports_2_getNonFullVCs,
       net_routers_router_core_3$EN_in_ports_2_putRoutedFlit,
       net_routers_router_core_3$EN_in_ports_3_getNonFullVCs,
       net_routers_router_core_3$EN_in_ports_3_putRoutedFlit,
       net_routers_router_core_3$EN_in_ports_4_getNonFullVCs,
       net_routers_router_core_3$EN_in_ports_4_putRoutedFlit,
       net_routers_router_core_3$EN_out_ports_0_getFlit,
       net_routers_router_core_3$EN_out_ports_0_putNonFullVCs,
       net_routers_router_core_3$EN_out_ports_1_getFlit,
       net_routers_router_core_3$EN_out_ports_1_putNonFullVCs,
       net_routers_router_core_3$EN_out_ports_2_getFlit,
       net_routers_router_core_3$EN_out_ports_2_putNonFullVCs,
       net_routers_router_core_3$EN_out_ports_3_getFlit,
       net_routers_router_core_3$EN_out_ports_3_putNonFullVCs,
       net_routers_router_core_3$EN_out_ports_4_getFlit,
       net_routers_router_core_3$EN_out_ports_4_putNonFullVCs;

  // actionvalue method send_ports_0_getNonFullVCs
  assign send_ports_0_getNonFullVCs =
	     net_routers_router_core$in_ports_0_getNonFullVCs ;

  // actionvalue method send_ports_1_getNonFullVCs
  assign send_ports_1_getNonFullVCs =
	     net_routers_router_core_1$in_ports_0_getNonFullVCs ;

  // actionvalue method send_ports_2_getNonFullVCs
  assign send_ports_2_getNonFullVCs =
	     net_routers_router_core_2$in_ports_0_getNonFullVCs ;

  // actionvalue method send_ports_3_getNonFullVCs
  assign send_ports_3_getNonFullVCs =
	     net_routers_router_core_3$in_ports_0_getNonFullVCs ;

  // actionvalue method recv_ports_0_getFlit
  assign recv_ports_0_getFlit = net_routers_router_core$out_ports_0_getFlit ;

  // actionvalue method recv_ports_1_getFlit
  assign recv_ports_1_getFlit =
	     net_routers_router_core_1$out_ports_0_getFlit ;

  // actionvalue method recv_ports_2_getFlit
  assign recv_ports_2_getFlit =
	     net_routers_router_core_2$out_ports_0_getFlit ;

  // actionvalue method recv_ports_3_getFlit
  assign recv_ports_3_getFlit =
	     net_routers_router_core_3$out_ports_0_getFlit ;

  // value method recv_ports_info_0_getRecvPortID
  assign recv_ports_info_0_getRecvPortID = 2'd0 ;

  // value method recv_ports_info_1_getRecvPortID
  assign recv_ports_info_1_getRecvPortID = 2'd1 ;

  // value method recv_ports_info_2_getRecvPortID
  assign recv_ports_info_2_getRecvPortID = 2'd2 ;

  // value method recv_ports_info_3_getRecvPortID
  assign recv_ports_info_3_getRecvPortID = 2'd3 ;

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_1.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_1_rt_ifc_banks_banks_rf(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf$ADDR_IN),
										     .D_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf$D_IN),
										     .WE(net_routers_routeTable_1_rt_ifc_banks_banks_rf$WE),
										     .D_OUT_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf$D_OUT_1));

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_1
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_1.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_1_rt_ifc_banks_banks_rf_1(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$ADDR_IN),
										       .D_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$D_IN),
										       .WE(net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$WE),
										       .D_OUT_1());

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_2
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_1.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_1_rt_ifc_banks_banks_rf_2(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$ADDR_IN),
										       .D_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$D_IN),
										       .WE(net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$WE),
										       .D_OUT_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$D_OUT_1));

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_3
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_1.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_1_rt_ifc_banks_banks_rf_3(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$ADDR_IN),
										       .D_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$D_IN),
										       .WE(net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$WE),
										       .D_OUT_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$D_OUT_1));

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_4
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_1.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_1_rt_ifc_banks_banks_rf_4(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$ADDR_IN),
										       .D_IN(net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$D_IN),
										       .WE(net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$WE),
										       .D_OUT_1());

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_2.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_2_rt_ifc_banks_banks_rf(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf$ADDR_IN),
										     .D_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf$D_IN),
										     .WE(net_routers_routeTable_2_rt_ifc_banks_banks_rf$WE),
										     .D_OUT_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf$D_OUT_1));

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_1
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_2.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_2_rt_ifc_banks_banks_rf_1(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$ADDR_IN),
										       .D_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$D_IN),
										       .WE(net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$WE),
										       .D_OUT_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$D_OUT_1));

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_2
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_2.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_2_rt_ifc_banks_banks_rf_2(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$ADDR_IN),
										       .D_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$D_IN),
										       .WE(net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$WE),
										       .D_OUT_1());

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_3
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_2.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_2_rt_ifc_banks_banks_rf_3(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$ADDR_IN),
										       .D_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$D_IN),
										       .WE(net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$WE),
										       .D_OUT_1());

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_4
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_2.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_2_rt_ifc_banks_banks_rf_4(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$ADDR_IN),
										       .D_IN(net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$D_IN),
										       .WE(net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$WE),
										       .D_OUT_1(net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$D_OUT_1));

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_3.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_3_rt_ifc_banks_banks_rf(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf$ADDR_IN),
										     .D_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf$D_IN),
										     .WE(net_routers_routeTable_3_rt_ifc_banks_banks_rf$WE),
										     .D_OUT_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf$D_OUT_1));

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_1
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_3.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_3_rt_ifc_banks_banks_rf_1(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$ADDR_IN),
										       .D_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$D_IN),
										       .WE(net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$WE),
										       .D_OUT_1());

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_2
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_3.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_3_rt_ifc_banks_banks_rf_2(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$ADDR_IN),
										       .D_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$D_IN),
										       .WE(net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$WE),
										       .D_OUT_1());

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_3
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_3.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_3_rt_ifc_banks_banks_rf_3(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$ADDR_IN),
										       .D_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$D_IN),
										       .WE(net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$WE),
										       .D_OUT_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$D_OUT_1));

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_4
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_3.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_3_rt_ifc_banks_banks_rf_4(.CLK(CLK),
										       .RST_N(RST_N),
										       .ADDR_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$ADDR_1),
										       .ADDR_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$ADDR_IN),
										       .D_IN(net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$D_IN),
										       .WE(net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$WE),
										       .D_OUT_1(net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$D_OUT_1));

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_0.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_rt_ifc_banks_banks_rf(.CLK(CLK),
										   .RST_N(RST_N),
										   .ADDR_1(net_routers_routeTable_rt_ifc_banks_banks_rf$ADDR_1),
										   .ADDR_IN(net_routers_routeTable_rt_ifc_banks_banks_rf$ADDR_IN),
										   .D_IN(net_routers_routeTable_rt_ifc_banks_banks_rf$D_IN),
										   .WE(net_routers_routeTable_rt_ifc_banks_banks_rf$WE),
										   .D_OUT_1(net_routers_routeTable_rt_ifc_banks_banks_rf$D_OUT_1));

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_1
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_0.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_rt_ifc_banks_banks_rf_1(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_rt_ifc_banks_banks_rf_1$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_1$ADDR_IN),
										     .D_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_1$D_IN),
										     .WE(net_routers_routeTable_rt_ifc_banks_banks_rf_1$WE),
										     .D_OUT_1(net_routers_routeTable_rt_ifc_banks_banks_rf_1$D_OUT_1));

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_2
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_0.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_rt_ifc_banks_banks_rf_2(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_rt_ifc_banks_banks_rf_2$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_2$ADDR_IN),
										     .D_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_2$D_IN),
										     .WE(net_routers_routeTable_rt_ifc_banks_banks_rf_2$WE),
										     .D_OUT_1(net_routers_routeTable_rt_ifc_banks_banks_rf_2$D_OUT_1));

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_3
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_0.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_rt_ifc_banks_banks_rf_3(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_rt_ifc_banks_banks_rf_3$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_3$ADDR_IN),
										     .D_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_3$D_IN),
										     .WE(net_routers_routeTable_rt_ifc_banks_banks_rf_3$WE),
										     .D_OUT_1());

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_4
  RegFileLoadSyn #( /*file*/ "mesh_4RTs_2VCs_8BD_32DW_SepIFRoundRobinAlloc_2RTsPerRow_2RTsPerCol_routing_0.hex",
		    /*addr_width*/ 32'd2,
		    /*data_width*/ 32'd3,
		    /*lo*/ 32'd0,
		    /*hi*/ 32'd3,
		    /*binary*/ 32'd0) net_routers_routeTable_rt_ifc_banks_banks_rf_4(.CLK(CLK),
										     .RST_N(RST_N),
										     .ADDR_1(net_routers_routeTable_rt_ifc_banks_banks_rf_4$ADDR_1),
										     .ADDR_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_4$ADDR_IN),
										     .D_IN(net_routers_routeTable_rt_ifc_banks_banks_rf_4$D_IN),
										     .WE(net_routers_routeTable_rt_ifc_banks_banks_rf_4$WE),
										     .D_OUT_1());

  // submodule net_routers_router_core
  mkIQRouterCoreSimple net_routers_router_core(.CLK(CLK),
					       .RST_N(RST_N),
					       .in_ports_0_putRoutedFlit_flit_in(net_routers_router_core$in_ports_0_putRoutedFlit_flit_in),
					       .in_ports_1_putRoutedFlit_flit_in(net_routers_router_core$in_ports_1_putRoutedFlit_flit_in),
					       .in_ports_2_putRoutedFlit_flit_in(net_routers_router_core$in_ports_2_putRoutedFlit_flit_in),
					       .in_ports_3_putRoutedFlit_flit_in(net_routers_router_core$in_ports_3_putRoutedFlit_flit_in),
					       .in_ports_4_putRoutedFlit_flit_in(net_routers_router_core$in_ports_4_putRoutedFlit_flit_in),
					       .out_ports_0_putNonFullVCs_nonFullVCs(net_routers_router_core$out_ports_0_putNonFullVCs_nonFullVCs),
					       .out_ports_1_putNonFullVCs_nonFullVCs(net_routers_router_core$out_ports_1_putNonFullVCs_nonFullVCs),
					       .out_ports_2_putNonFullVCs_nonFullVCs(net_routers_router_core$out_ports_2_putNonFullVCs_nonFullVCs),
					       .out_ports_3_putNonFullVCs_nonFullVCs(net_routers_router_core$out_ports_3_putNonFullVCs_nonFullVCs),
					       .out_ports_4_putNonFullVCs_nonFullVCs(net_routers_router_core$out_ports_4_putNonFullVCs_nonFullVCs),
					       .EN_in_ports_0_putRoutedFlit(net_routers_router_core$EN_in_ports_0_putRoutedFlit),
					       .EN_in_ports_0_getNonFullVCs(net_routers_router_core$EN_in_ports_0_getNonFullVCs),
					       .EN_in_ports_1_putRoutedFlit(net_routers_router_core$EN_in_ports_1_putRoutedFlit),
					       .EN_in_ports_1_getNonFullVCs(net_routers_router_core$EN_in_ports_1_getNonFullVCs),
					       .EN_in_ports_2_putRoutedFlit(net_routers_router_core$EN_in_ports_2_putRoutedFlit),
					       .EN_in_ports_2_getNonFullVCs(net_routers_router_core$EN_in_ports_2_getNonFullVCs),
					       .EN_in_ports_3_putRoutedFlit(net_routers_router_core$EN_in_ports_3_putRoutedFlit),
					       .EN_in_ports_3_getNonFullVCs(net_routers_router_core$EN_in_ports_3_getNonFullVCs),
					       .EN_in_ports_4_putRoutedFlit(net_routers_router_core$EN_in_ports_4_putRoutedFlit),
					       .EN_in_ports_4_getNonFullVCs(net_routers_router_core$EN_in_ports_4_getNonFullVCs),
					       .EN_out_ports_0_getFlit(net_routers_router_core$EN_out_ports_0_getFlit),
					       .EN_out_ports_0_putNonFullVCs(net_routers_router_core$EN_out_ports_0_putNonFullVCs),
					       .EN_out_ports_1_getFlit(net_routers_router_core$EN_out_ports_1_getFlit),
					       .EN_out_ports_1_putNonFullVCs(net_routers_router_core$EN_out_ports_1_putNonFullVCs),
					       .EN_out_ports_2_getFlit(net_routers_router_core$EN_out_ports_2_getFlit),
					       .EN_out_ports_2_putNonFullVCs(net_routers_router_core$EN_out_ports_2_putNonFullVCs),
					       .EN_out_ports_3_getFlit(net_routers_router_core$EN_out_ports_3_getFlit),
					       .EN_out_ports_3_putNonFullVCs(net_routers_router_core$EN_out_ports_3_putNonFullVCs),
					       .EN_out_ports_4_getFlit(net_routers_router_core$EN_out_ports_4_getFlit),
					       .EN_out_ports_4_putNonFullVCs(net_routers_router_core$EN_out_ports_4_putNonFullVCs),
					       .in_ports_0_getNonFullVCs(net_routers_router_core$in_ports_0_getNonFullVCs),
					       .in_ports_1_getNonFullVCs(net_routers_router_core$in_ports_1_getNonFullVCs),
					       .in_ports_2_getNonFullVCs(net_routers_router_core$in_ports_2_getNonFullVCs),
					       .in_ports_3_getNonFullVCs(),
					       .in_ports_4_getNonFullVCs(),
					       .out_ports_0_getFlit(net_routers_router_core$out_ports_0_getFlit),
					       .out_ports_1_getFlit(),
					       .out_ports_2_getFlit(),
					       .out_ports_3_getFlit(net_routers_router_core$out_ports_3_getFlit),
					       .out_ports_4_getFlit(net_routers_router_core$out_ports_4_getFlit));

  // submodule net_routers_router_core_1
  mkIQRouterCoreSimple net_routers_router_core_1(.CLK(CLK),
						 .RST_N(RST_N),
						 .in_ports_0_putRoutedFlit_flit_in(net_routers_router_core_1$in_ports_0_putRoutedFlit_flit_in),
						 .in_ports_1_putRoutedFlit_flit_in(net_routers_router_core_1$in_ports_1_putRoutedFlit_flit_in),
						 .in_ports_2_putRoutedFlit_flit_in(net_routers_router_core_1$in_ports_2_putRoutedFlit_flit_in),
						 .in_ports_3_putRoutedFlit_flit_in(net_routers_router_core_1$in_ports_3_putRoutedFlit_flit_in),
						 .in_ports_4_putRoutedFlit_flit_in(net_routers_router_core_1$in_ports_4_putRoutedFlit_flit_in),
						 .out_ports_0_putNonFullVCs_nonFullVCs(net_routers_router_core_1$out_ports_0_putNonFullVCs_nonFullVCs),
						 .out_ports_1_putNonFullVCs_nonFullVCs(net_routers_router_core_1$out_ports_1_putNonFullVCs_nonFullVCs),
						 .out_ports_2_putNonFullVCs_nonFullVCs(net_routers_router_core_1$out_ports_2_putNonFullVCs_nonFullVCs),
						 .out_ports_3_putNonFullVCs_nonFullVCs(net_routers_router_core_1$out_ports_3_putNonFullVCs_nonFullVCs),
						 .out_ports_4_putNonFullVCs_nonFullVCs(net_routers_router_core_1$out_ports_4_putNonFullVCs_nonFullVCs),
						 .EN_in_ports_0_putRoutedFlit(net_routers_router_core_1$EN_in_ports_0_putRoutedFlit),
						 .EN_in_ports_0_getNonFullVCs(net_routers_router_core_1$EN_in_ports_0_getNonFullVCs),
						 .EN_in_ports_1_putRoutedFlit(net_routers_router_core_1$EN_in_ports_1_putRoutedFlit),
						 .EN_in_ports_1_getNonFullVCs(net_routers_router_core_1$EN_in_ports_1_getNonFullVCs),
						 .EN_in_ports_2_putRoutedFlit(net_routers_router_core_1$EN_in_ports_2_putRoutedFlit),
						 .EN_in_ports_2_getNonFullVCs(net_routers_router_core_1$EN_in_ports_2_getNonFullVCs),
						 .EN_in_ports_3_putRoutedFlit(net_routers_router_core_1$EN_in_ports_3_putRoutedFlit),
						 .EN_in_ports_3_getNonFullVCs(net_routers_router_core_1$EN_in_ports_3_getNonFullVCs),
						 .EN_in_ports_4_putRoutedFlit(net_routers_router_core_1$EN_in_ports_4_putRoutedFlit),
						 .EN_in_ports_4_getNonFullVCs(net_routers_router_core_1$EN_in_ports_4_getNonFullVCs),
						 .EN_out_ports_0_getFlit(net_routers_router_core_1$EN_out_ports_0_getFlit),
						 .EN_out_ports_0_putNonFullVCs(net_routers_router_core_1$EN_out_ports_0_putNonFullVCs),
						 .EN_out_ports_1_getFlit(net_routers_router_core_1$EN_out_ports_1_getFlit),
						 .EN_out_ports_1_putNonFullVCs(net_routers_router_core_1$EN_out_ports_1_putNonFullVCs),
						 .EN_out_ports_2_getFlit(net_routers_router_core_1$EN_out_ports_2_getFlit),
						 .EN_out_ports_2_putNonFullVCs(net_routers_router_core_1$EN_out_ports_2_putNonFullVCs),
						 .EN_out_ports_3_getFlit(net_routers_router_core_1$EN_out_ports_3_getFlit),
						 .EN_out_ports_3_putNonFullVCs(net_routers_router_core_1$EN_out_ports_3_putNonFullVCs),
						 .EN_out_ports_4_getFlit(net_routers_router_core_1$EN_out_ports_4_getFlit),
						 .EN_out_ports_4_putNonFullVCs(net_routers_router_core_1$EN_out_ports_4_putNonFullVCs),
						 .in_ports_0_getNonFullVCs(net_routers_router_core_1$in_ports_0_getNonFullVCs),
						 .in_ports_1_getNonFullVCs(),
						 .in_ports_2_getNonFullVCs(net_routers_router_core_1$in_ports_2_getNonFullVCs),
						 .in_ports_3_getNonFullVCs(net_routers_router_core_1$in_ports_3_getNonFullVCs),
						 .in_ports_4_getNonFullVCs(),
						 .out_ports_0_getFlit(net_routers_router_core_1$out_ports_0_getFlit),
						 .out_ports_1_getFlit(net_routers_router_core_1$out_ports_1_getFlit),
						 .out_ports_2_getFlit(),
						 .out_ports_3_getFlit(),
						 .out_ports_4_getFlit(net_routers_router_core_1$out_ports_4_getFlit));

  // submodule net_routers_router_core_2
  mkIQRouterCoreSimple net_routers_router_core_2(.CLK(CLK),
						 .RST_N(RST_N),
						 .in_ports_0_putRoutedFlit_flit_in(net_routers_router_core_2$in_ports_0_putRoutedFlit_flit_in),
						 .in_ports_1_putRoutedFlit_flit_in(net_routers_router_core_2$in_ports_1_putRoutedFlit_flit_in),
						 .in_ports_2_putRoutedFlit_flit_in(net_routers_router_core_2$in_ports_2_putRoutedFlit_flit_in),
						 .in_ports_3_putRoutedFlit_flit_in(net_routers_router_core_2$in_ports_3_putRoutedFlit_flit_in),
						 .in_ports_4_putRoutedFlit_flit_in(net_routers_router_core_2$in_ports_4_putRoutedFlit_flit_in),
						 .out_ports_0_putNonFullVCs_nonFullVCs(net_routers_router_core_2$out_ports_0_putNonFullVCs_nonFullVCs),
						 .out_ports_1_putNonFullVCs_nonFullVCs(net_routers_router_core_2$out_ports_1_putNonFullVCs_nonFullVCs),
						 .out_ports_2_putNonFullVCs_nonFullVCs(net_routers_router_core_2$out_ports_2_putNonFullVCs_nonFullVCs),
						 .out_ports_3_putNonFullVCs_nonFullVCs(net_routers_router_core_2$out_ports_3_putNonFullVCs_nonFullVCs),
						 .out_ports_4_putNonFullVCs_nonFullVCs(net_routers_router_core_2$out_ports_4_putNonFullVCs_nonFullVCs),
						 .EN_in_ports_0_putRoutedFlit(net_routers_router_core_2$EN_in_ports_0_putRoutedFlit),
						 .EN_in_ports_0_getNonFullVCs(net_routers_router_core_2$EN_in_ports_0_getNonFullVCs),
						 .EN_in_ports_1_putRoutedFlit(net_routers_router_core_2$EN_in_ports_1_putRoutedFlit),
						 .EN_in_ports_1_getNonFullVCs(net_routers_router_core_2$EN_in_ports_1_getNonFullVCs),
						 .EN_in_ports_2_putRoutedFlit(net_routers_router_core_2$EN_in_ports_2_putRoutedFlit),
						 .EN_in_ports_2_getNonFullVCs(net_routers_router_core_2$EN_in_ports_2_getNonFullVCs),
						 .EN_in_ports_3_putRoutedFlit(net_routers_router_core_2$EN_in_ports_3_putRoutedFlit),
						 .EN_in_ports_3_getNonFullVCs(net_routers_router_core_2$EN_in_ports_3_getNonFullVCs),
						 .EN_in_ports_4_putRoutedFlit(net_routers_router_core_2$EN_in_ports_4_putRoutedFlit),
						 .EN_in_ports_4_getNonFullVCs(net_routers_router_core_2$EN_in_ports_4_getNonFullVCs),
						 .EN_out_ports_0_getFlit(net_routers_router_core_2$EN_out_ports_0_getFlit),
						 .EN_out_ports_0_putNonFullVCs(net_routers_router_core_2$EN_out_ports_0_putNonFullVCs),
						 .EN_out_ports_1_getFlit(net_routers_router_core_2$EN_out_ports_1_getFlit),
						 .EN_out_ports_1_putNonFullVCs(net_routers_router_core_2$EN_out_ports_1_putNonFullVCs),
						 .EN_out_ports_2_getFlit(net_routers_router_core_2$EN_out_ports_2_getFlit),
						 .EN_out_ports_2_putNonFullVCs(net_routers_router_core_2$EN_out_ports_2_putNonFullVCs),
						 .EN_out_ports_3_getFlit(net_routers_router_core_2$EN_out_ports_3_getFlit),
						 .EN_out_ports_3_putNonFullVCs(net_routers_router_core_2$EN_out_ports_3_putNonFullVCs),
						 .EN_out_ports_4_getFlit(net_routers_router_core_2$EN_out_ports_4_getFlit),
						 .EN_out_ports_4_putNonFullVCs(net_routers_router_core_2$EN_out_ports_4_putNonFullVCs),
						 .in_ports_0_getNonFullVCs(net_routers_router_core_2$in_ports_0_getNonFullVCs),
						 .in_ports_1_getNonFullVCs(net_routers_router_core_2$in_ports_1_getNonFullVCs),
						 .in_ports_2_getNonFullVCs(),
						 .in_ports_3_getNonFullVCs(),
						 .in_ports_4_getNonFullVCs(net_routers_router_core_2$in_ports_4_getNonFullVCs),
						 .out_ports_0_getFlit(net_routers_router_core_2$out_ports_0_getFlit),
						 .out_ports_1_getFlit(),
						 .out_ports_2_getFlit(net_routers_router_core_2$out_ports_2_getFlit),
						 .out_ports_3_getFlit(net_routers_router_core_2$out_ports_3_getFlit),
						 .out_ports_4_getFlit());

  // submodule net_routers_router_core_3
  mkIQRouterCoreSimple net_routers_router_core_3(.CLK(CLK),
						 .RST_N(RST_N),
						 .in_ports_0_putRoutedFlit_flit_in(net_routers_router_core_3$in_ports_0_putRoutedFlit_flit_in),
						 .in_ports_1_putRoutedFlit_flit_in(net_routers_router_core_3$in_ports_1_putRoutedFlit_flit_in),
						 .in_ports_2_putRoutedFlit_flit_in(net_routers_router_core_3$in_ports_2_putRoutedFlit_flit_in),
						 .in_ports_3_putRoutedFlit_flit_in(net_routers_router_core_3$in_ports_3_putRoutedFlit_flit_in),
						 .in_ports_4_putRoutedFlit_flit_in(net_routers_router_core_3$in_ports_4_putRoutedFlit_flit_in),
						 .out_ports_0_putNonFullVCs_nonFullVCs(net_routers_router_core_3$out_ports_0_putNonFullVCs_nonFullVCs),
						 .out_ports_1_putNonFullVCs_nonFullVCs(net_routers_router_core_3$out_ports_1_putNonFullVCs_nonFullVCs),
						 .out_ports_2_putNonFullVCs_nonFullVCs(net_routers_router_core_3$out_ports_2_putNonFullVCs_nonFullVCs),
						 .out_ports_3_putNonFullVCs_nonFullVCs(net_routers_router_core_3$out_ports_3_putNonFullVCs_nonFullVCs),
						 .out_ports_4_putNonFullVCs_nonFullVCs(net_routers_router_core_3$out_ports_4_putNonFullVCs_nonFullVCs),
						 .EN_in_ports_0_putRoutedFlit(net_routers_router_core_3$EN_in_ports_0_putRoutedFlit),
						 .EN_in_ports_0_getNonFullVCs(net_routers_router_core_3$EN_in_ports_0_getNonFullVCs),
						 .EN_in_ports_1_putRoutedFlit(net_routers_router_core_3$EN_in_ports_1_putRoutedFlit),
						 .EN_in_ports_1_getNonFullVCs(net_routers_router_core_3$EN_in_ports_1_getNonFullVCs),
						 .EN_in_ports_2_putRoutedFlit(net_routers_router_core_3$EN_in_ports_2_putRoutedFlit),
						 .EN_in_ports_2_getNonFullVCs(net_routers_router_core_3$EN_in_ports_2_getNonFullVCs),
						 .EN_in_ports_3_putRoutedFlit(net_routers_router_core_3$EN_in_ports_3_putRoutedFlit),
						 .EN_in_ports_3_getNonFullVCs(net_routers_router_core_3$EN_in_ports_3_getNonFullVCs),
						 .EN_in_ports_4_putRoutedFlit(net_routers_router_core_3$EN_in_ports_4_putRoutedFlit),
						 .EN_in_ports_4_getNonFullVCs(net_routers_router_core_3$EN_in_ports_4_getNonFullVCs),
						 .EN_out_ports_0_getFlit(net_routers_router_core_3$EN_out_ports_0_getFlit),
						 .EN_out_ports_0_putNonFullVCs(net_routers_router_core_3$EN_out_ports_0_putNonFullVCs),
						 .EN_out_ports_1_getFlit(net_routers_router_core_3$EN_out_ports_1_getFlit),
						 .EN_out_ports_1_putNonFullVCs(net_routers_router_core_3$EN_out_ports_1_putNonFullVCs),
						 .EN_out_ports_2_getFlit(net_routers_router_core_3$EN_out_ports_2_getFlit),
						 .EN_out_ports_2_putNonFullVCs(net_routers_router_core_3$EN_out_ports_2_putNonFullVCs),
						 .EN_out_ports_3_getFlit(net_routers_router_core_3$EN_out_ports_3_getFlit),
						 .EN_out_ports_3_putNonFullVCs(net_routers_router_core_3$EN_out_ports_3_putNonFullVCs),
						 .EN_out_ports_4_getFlit(net_routers_router_core_3$EN_out_ports_4_getFlit),
						 .EN_out_ports_4_putNonFullVCs(net_routers_router_core_3$EN_out_ports_4_putNonFullVCs),
						 .in_ports_0_getNonFullVCs(net_routers_router_core_3$in_ports_0_getNonFullVCs),
						 .in_ports_1_getNonFullVCs(),
						 .in_ports_2_getNonFullVCs(),
						 .in_ports_3_getNonFullVCs(net_routers_router_core_3$in_ports_3_getNonFullVCs),
						 .in_ports_4_getNonFullVCs(net_routers_router_core_3$in_ports_4_getNonFullVCs),
						 .out_ports_0_getFlit(net_routers_router_core_3$out_ports_0_getFlit),
						 .out_ports_1_getFlit(net_routers_router_core_3$out_ports_1_getFlit),
						 .out_ports_2_getFlit(net_routers_router_core_3$out_ports_2_getFlit),
						 .out_ports_3_getFlit(),
						 .out_ports_4_getFlit());

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf$ADDR_1 =
	     send_ports_1_putFlit_flit_in[34:33] ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf$D_IN = 3'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf$WE = 1'b0 ;

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_1
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$D_IN = 3'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_1$WE = 1'b0 ;

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_2
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$ADDR_1 =
	     net_routers_router_core_3$out_ports_2_getFlit[34:33] ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$D_IN = 3'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$WE = 1'b0 ;

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_3
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$ADDR_1 =
	     net_routers_router_core$out_ports_3_getFlit[34:33] ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$D_IN = 3'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$WE = 1'b0 ;

  // submodule net_routers_routeTable_1_rt_ifc_banks_banks_rf_4
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$D_IN = 3'h0 ;
  assign net_routers_routeTable_1_rt_ifc_banks_banks_rf_4$WE = 1'b0 ;

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf$ADDR_1 =
	     send_ports_2_putFlit_flit_in[34:33] ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf$D_IN = 3'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf$WE = 1'b0 ;

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_1
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$ADDR_1 =
	     net_routers_router_core_3$out_ports_1_getFlit[34:33] ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$D_IN = 3'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$WE = 1'b0 ;

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_2
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$D_IN = 3'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_2$WE = 1'b0 ;

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_3
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$D_IN = 3'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_3$WE = 1'b0 ;

  // submodule net_routers_routeTable_2_rt_ifc_banks_banks_rf_4
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$ADDR_1 =
	     net_routers_router_core$out_ports_4_getFlit[34:33] ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$D_IN = 3'h0 ;
  assign net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$WE = 1'b0 ;

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf$ADDR_1 =
	     send_ports_3_putFlit_flit_in[34:33] ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf$D_IN = 3'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf$WE = 1'b0 ;

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_1
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$D_IN = 3'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_1$WE = 1'b0 ;

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_2
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$D_IN = 3'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_2$WE = 1'b0 ;

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_3
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$ADDR_1 =
	     net_routers_router_core_2$out_ports_3_getFlit[34:33] ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$D_IN = 3'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$WE = 1'b0 ;

  // submodule net_routers_routeTable_3_rt_ifc_banks_banks_rf_4
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$ADDR_1 =
	     net_routers_router_core_1$out_ports_4_getFlit[34:33] ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$D_IN = 3'h0 ;
  assign net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$WE = 1'b0 ;

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf
  assign net_routers_routeTable_rt_ifc_banks_banks_rf$ADDR_1 =
	     send_ports_0_putFlit_flit_in[34:33] ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf$D_IN = 3'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf$WE = 1'b0 ;

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_1
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_1$ADDR_1 =
	     net_routers_router_core_1$out_ports_1_getFlit[34:33] ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_1$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_1$D_IN = 3'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_1$WE = 1'b0 ;

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_2
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_2$ADDR_1 =
	     net_routers_router_core_2$out_ports_2_getFlit[34:33] ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_2$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_2$D_IN = 3'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_2$WE = 1'b0 ;

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_3
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_3$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_3$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_3$D_IN = 3'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_3$WE = 1'b0 ;

  // submodule net_routers_routeTable_rt_ifc_banks_banks_rf_4
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_4$ADDR_1 = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_4$ADDR_IN = 2'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_4$D_IN = 3'h0 ;
  assign net_routers_routeTable_rt_ifc_banks_banks_rf_4$WE = 1'b0 ;

  // submodule net_routers_router_core
  assign net_routers_router_core$in_ports_0_putRoutedFlit_flit_in =
	     { send_ports_0_putFlit_flit_in,
	       net_routers_routeTable_rt_ifc_banks_banks_rf$D_OUT_1 } ;
  assign net_routers_router_core$in_ports_1_putRoutedFlit_flit_in =
	     { net_routers_router_core_1$out_ports_1_getFlit,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_1$D_OUT_1 } ;
  assign net_routers_router_core$in_ports_2_putRoutedFlit_flit_in =
	     { net_routers_router_core_2$out_ports_2_getFlit,
	       net_routers_routeTable_rt_ifc_banks_banks_rf_2$D_OUT_1 } ;
  assign net_routers_router_core$in_ports_3_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core$in_ports_4_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core$out_ports_0_putNonFullVCs_nonFullVCs =
	     recv_ports_0_putNonFullVCs_nonFullVCs ;
  assign net_routers_router_core$out_ports_1_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign net_routers_router_core$out_ports_2_putNonFullVCs_nonFullVCs = 2'h0 ;
  assign net_routers_router_core$out_ports_3_putNonFullVCs_nonFullVCs =
	     net_routers_router_core_1$in_ports_3_getNonFullVCs ;
  assign net_routers_router_core$out_ports_4_putNonFullVCs_nonFullVCs =
	     net_routers_router_core_2$in_ports_4_getNonFullVCs ;
  assign net_routers_router_core$EN_in_ports_0_putRoutedFlit =
	     EN_send_ports_0_putFlit ;
  assign net_routers_router_core$EN_in_ports_0_getNonFullVCs =
	     EN_send_ports_0_getNonFullVCs ;
  assign net_routers_router_core$EN_in_ports_1_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core$EN_in_ports_1_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core$EN_in_ports_2_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core$EN_in_ports_2_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core$EN_in_ports_3_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core$EN_in_ports_3_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core$EN_in_ports_4_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core$EN_in_ports_4_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core$EN_out_ports_0_getFlit =
	     EN_recv_ports_0_getFlit ;
  assign net_routers_router_core$EN_out_ports_0_putNonFullVCs =
	     EN_recv_ports_0_putNonFullVCs ;
  assign net_routers_router_core$EN_out_ports_1_getFlit = 1'b0 ;
  assign net_routers_router_core$EN_out_ports_1_putNonFullVCs = 1'b0 ;
  assign net_routers_router_core$EN_out_ports_2_getFlit = 1'b0 ;
  assign net_routers_router_core$EN_out_ports_2_putNonFullVCs = 1'b0 ;
  assign net_routers_router_core$EN_out_ports_3_getFlit = 1'd1 ;
  assign net_routers_router_core$EN_out_ports_3_putNonFullVCs = 1'd1 ;
  assign net_routers_router_core$EN_out_ports_4_getFlit = 1'd1 ;
  assign net_routers_router_core$EN_out_ports_4_putNonFullVCs = 1'd1 ;

  // submodule net_routers_router_core_1
  assign net_routers_router_core_1$in_ports_0_putRoutedFlit_flit_in =
	     { send_ports_1_putFlit_flit_in,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf$D_OUT_1 } ;
  assign net_routers_router_core_1$in_ports_1_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core_1$in_ports_2_putRoutedFlit_flit_in =
	     { net_routers_router_core_3$out_ports_2_getFlit,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_2$D_OUT_1 } ;
  assign net_routers_router_core_1$in_ports_3_putRoutedFlit_flit_in =
	     { net_routers_router_core$out_ports_3_getFlit,
	       net_routers_routeTable_1_rt_ifc_banks_banks_rf_3$D_OUT_1 } ;
  assign net_routers_router_core_1$in_ports_4_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core_1$out_ports_0_putNonFullVCs_nonFullVCs =
	     recv_ports_1_putNonFullVCs_nonFullVCs ;
  assign net_routers_router_core_1$out_ports_1_putNonFullVCs_nonFullVCs =
	     net_routers_router_core$in_ports_1_getNonFullVCs ;
  assign net_routers_router_core_1$out_ports_2_putNonFullVCs_nonFullVCs =
	     2'h0 ;
  assign net_routers_router_core_1$out_ports_3_putNonFullVCs_nonFullVCs =
	     2'h0 ;
  assign net_routers_router_core_1$out_ports_4_putNonFullVCs_nonFullVCs =
	     net_routers_router_core_3$in_ports_4_getNonFullVCs ;
  assign net_routers_router_core_1$EN_in_ports_0_putRoutedFlit =
	     EN_send_ports_1_putFlit ;
  assign net_routers_router_core_1$EN_in_ports_0_getNonFullVCs =
	     EN_send_ports_1_getNonFullVCs ;
  assign net_routers_router_core_1$EN_in_ports_1_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core_1$EN_in_ports_1_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core_1$EN_in_ports_2_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core_1$EN_in_ports_2_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core_1$EN_in_ports_3_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core_1$EN_in_ports_3_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core_1$EN_in_ports_4_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core_1$EN_in_ports_4_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core_1$EN_out_ports_0_getFlit =
	     EN_recv_ports_1_getFlit ;
  assign net_routers_router_core_1$EN_out_ports_0_putNonFullVCs =
	     EN_recv_ports_1_putNonFullVCs ;
  assign net_routers_router_core_1$EN_out_ports_1_getFlit = 1'd1 ;
  assign net_routers_router_core_1$EN_out_ports_1_putNonFullVCs = 1'd1 ;
  assign net_routers_router_core_1$EN_out_ports_2_getFlit = 1'b0 ;
  assign net_routers_router_core_1$EN_out_ports_2_putNonFullVCs = 1'b0 ;
  assign net_routers_router_core_1$EN_out_ports_3_getFlit = 1'b0 ;
  assign net_routers_router_core_1$EN_out_ports_3_putNonFullVCs = 1'b0 ;
  assign net_routers_router_core_1$EN_out_ports_4_getFlit = 1'd1 ;
  assign net_routers_router_core_1$EN_out_ports_4_putNonFullVCs = 1'd1 ;

  // submodule net_routers_router_core_2
  assign net_routers_router_core_2$in_ports_0_putRoutedFlit_flit_in =
	     { send_ports_2_putFlit_flit_in,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf$D_OUT_1 } ;
  assign net_routers_router_core_2$in_ports_1_putRoutedFlit_flit_in =
	     { net_routers_router_core_3$out_ports_1_getFlit,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_1$D_OUT_1 } ;
  assign net_routers_router_core_2$in_ports_2_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core_2$in_ports_3_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core_2$in_ports_4_putRoutedFlit_flit_in =
	     { net_routers_router_core$out_ports_4_getFlit,
	       net_routers_routeTable_2_rt_ifc_banks_banks_rf_4$D_OUT_1 } ;
  assign net_routers_router_core_2$out_ports_0_putNonFullVCs_nonFullVCs =
	     recv_ports_2_putNonFullVCs_nonFullVCs ;
  assign net_routers_router_core_2$out_ports_1_putNonFullVCs_nonFullVCs =
	     2'h0 ;
  assign net_routers_router_core_2$out_ports_2_putNonFullVCs_nonFullVCs =
	     net_routers_router_core$in_ports_2_getNonFullVCs ;
  assign net_routers_router_core_2$out_ports_3_putNonFullVCs_nonFullVCs =
	     net_routers_router_core_3$in_ports_3_getNonFullVCs ;
  assign net_routers_router_core_2$out_ports_4_putNonFullVCs_nonFullVCs =
	     2'h0 ;
  assign net_routers_router_core_2$EN_in_ports_0_putRoutedFlit =
	     EN_send_ports_2_putFlit ;
  assign net_routers_router_core_2$EN_in_ports_0_getNonFullVCs =
	     EN_send_ports_2_getNonFullVCs ;
  assign net_routers_router_core_2$EN_in_ports_1_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core_2$EN_in_ports_1_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core_2$EN_in_ports_2_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core_2$EN_in_ports_2_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core_2$EN_in_ports_3_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core_2$EN_in_ports_3_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core_2$EN_in_ports_4_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core_2$EN_in_ports_4_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core_2$EN_out_ports_0_getFlit =
	     EN_recv_ports_2_getFlit ;
  assign net_routers_router_core_2$EN_out_ports_0_putNonFullVCs =
	     EN_recv_ports_2_putNonFullVCs ;
  assign net_routers_router_core_2$EN_out_ports_1_getFlit = 1'b0 ;
  assign net_routers_router_core_2$EN_out_ports_1_putNonFullVCs = 1'b0 ;
  assign net_routers_router_core_2$EN_out_ports_2_getFlit = 1'd1 ;
  assign net_routers_router_core_2$EN_out_ports_2_putNonFullVCs = 1'd1 ;
  assign net_routers_router_core_2$EN_out_ports_3_getFlit = 1'd1 ;
  assign net_routers_router_core_2$EN_out_ports_3_putNonFullVCs = 1'd1 ;
  assign net_routers_router_core_2$EN_out_ports_4_getFlit = 1'b0 ;
  assign net_routers_router_core_2$EN_out_ports_4_putNonFullVCs = 1'b0 ;

  // submodule net_routers_router_core_3
  assign net_routers_router_core_3$in_ports_0_putRoutedFlit_flit_in =
	     { send_ports_3_putFlit_flit_in,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf$D_OUT_1 } ;
  assign net_routers_router_core_3$in_ports_1_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core_3$in_ports_2_putRoutedFlit_flit_in = 40'h0 ;
  assign net_routers_router_core_3$in_ports_3_putRoutedFlit_flit_in =
	     { net_routers_router_core_2$out_ports_3_getFlit,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_3$D_OUT_1 } ;
  assign net_routers_router_core_3$in_ports_4_putRoutedFlit_flit_in =
	     { net_routers_router_core_1$out_ports_4_getFlit,
	       net_routers_routeTable_3_rt_ifc_banks_banks_rf_4$D_OUT_1 } ;
  assign net_routers_router_core_3$out_ports_0_putNonFullVCs_nonFullVCs =
	     recv_ports_3_putNonFullVCs_nonFullVCs ;
  assign net_routers_router_core_3$out_ports_1_putNonFullVCs_nonFullVCs =
	     net_routers_router_core_2$in_ports_1_getNonFullVCs ;
  assign net_routers_router_core_3$out_ports_2_putNonFullVCs_nonFullVCs =
	     net_routers_router_core_1$in_ports_2_getNonFullVCs ;
  assign net_routers_router_core_3$out_ports_3_putNonFullVCs_nonFullVCs =
	     2'h0 ;
  assign net_routers_router_core_3$out_ports_4_putNonFullVCs_nonFullVCs =
	     2'h0 ;
  assign net_routers_router_core_3$EN_in_ports_0_putRoutedFlit =
	     EN_send_ports_3_putFlit ;
  assign net_routers_router_core_3$EN_in_ports_0_getNonFullVCs =
	     EN_send_ports_3_getNonFullVCs ;
  assign net_routers_router_core_3$EN_in_ports_1_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core_3$EN_in_ports_1_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core_3$EN_in_ports_2_putRoutedFlit = 1'b0 ;
  assign net_routers_router_core_3$EN_in_ports_2_getNonFullVCs = 1'b0 ;
  assign net_routers_router_core_3$EN_in_ports_3_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core_3$EN_in_ports_3_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core_3$EN_in_ports_4_putRoutedFlit = 1'd1 ;
  assign net_routers_router_core_3$EN_in_ports_4_getNonFullVCs = 1'd1 ;
  assign net_routers_router_core_3$EN_out_ports_0_getFlit =
	     EN_recv_ports_3_getFlit ;
  assign net_routers_router_core_3$EN_out_ports_0_putNonFullVCs =
	     EN_recv_ports_3_putNonFullVCs ;
  assign net_routers_router_core_3$EN_out_ports_1_getFlit = 1'd1 ;
  assign net_routers_router_core_3$EN_out_ports_1_putNonFullVCs = 1'd1 ;
  assign net_routers_router_core_3$EN_out_ports_2_getFlit = 1'd1 ;
  assign net_routers_router_core_3$EN_out_ports_2_putNonFullVCs = 1'd1 ;
  assign net_routers_router_core_3$EN_out_ports_3_getFlit = 1'b0 ;
  assign net_routers_router_core_3$EN_out_ports_3_putNonFullVCs = 1'b0 ;
  assign net_routers_router_core_3$EN_out_ports_4_getFlit = 1'b0 ;
  assign net_routers_router_core_3$EN_out_ports_4_putNonFullVCs = 1'b0 ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N)
      if (EN_send_ports_0_putFlit && send_ports_0_putFlit_flit_in[36])
	$write("");
    if (RST_N)
      if (EN_send_ports_1_putFlit && send_ports_1_putFlit_flit_in[36])
	$write("");
    if (RST_N)
      if (EN_send_ports_2_putFlit && send_ports_2_putFlit_flit_in[36])
	$write("");
    if (RST_N)
      if (EN_send_ports_3_putFlit && send_ports_3_putFlit_flit_in[36])
	$write("");
    if (RST_N)
      if (net_routers_router_core_1$out_ports_1_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core_3$out_ports_1_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core_2$out_ports_2_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core_3$out_ports_2_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core$out_ports_3_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core_2$out_ports_3_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core$out_ports_4_getFlit[36]) $write("");
    if (RST_N)
      if (net_routers_router_core_1$out_ports_4_getFlit[36]) $write("");
  end
  // synopsys translate_on
endmodule  // mkNetworkSimple

