#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Nov 27 16:33:46 +06 2017
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvlog --incr --relax -prj Test_tb_vlog.prj"
ExecStep xvlog --incr --relax -prj Test_tb_vlog.prj 2>&1 | tee compile.log
echo "xvhdl --incr --relax -prj Test_tb_vhdl.prj"
ExecStep xvhdl --incr --relax -prj Test_tb_vhdl.prj 2>&1 | tee -a compile.log
