/*
 * These source files contain a hardware description of a network
 * automatically generated by CONNECT (CONfigurable NEtwork Creation Tool).
 *
 * This product includes a hardware design developed by Carnegie Mellon
 * University.
 *
 * Copyright (c) 2012 by Michael K. Papamichael, Carnegie Mellon University
 *
 * For more information, see the CONNECT project website at:
 *   http://www.ece.cmu.edu/~mpapamic/connect
 *
 * This design is provided for internal, non-commercial research use only, 
 * cannot be used for, or in support of, goods or services, and is not for
 * redistribution, with or without modifications.
 * 
 * You may not use the name "Carnegie Mellon University" or derivations
 * thereof to endorse or promote products derived from this software.
 *
 * THE SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER
 * EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO ANY WARRANTY
 * THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS OR BE ERROR-FREE AND ANY
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
 * TITLE, OR NON-INFRINGEMENT.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
 * BE LIABLE FOR ANY DAMAGES, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT,
 * SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM, OR IN
 * ANY WAY CONNECTED WITH THIS SOFTWARE (WHETHER OR NOT BASED UPON WARRANTY,
 * CONTRACT, TORT OR OTHERWISE).
 *
 */


//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Sun Jun 10 13:14:19 EDT 2018
//
// Method conflict info:
// Method: select
// Conflict-free: select
// Sequenced before: next
//
// Method: next
// Sequenced after: select
// Conflicts: next
//
//
// Ports:
// Name                         I/O  size props
// select                         O    16
// CLK                            I     1 clock
// RST_N                          I     1 reset
// select_requests                I    16
// EN_next                        I     1
//
// Combinational paths from inputs to outputs:
//   select_requests -> select
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module mkOutputArbiter(CLK,
		       RST_N,

		       select_requests,
		       select,

		       EN_next);
  input  CLK;
  input  RST_N;

  // value method select
  input  [15 : 0] select_requests;
  output [15 : 0] select;

  // action method next
  input  EN_next;

  // signals for module outputs
  wire [15 : 0] select;

  // register arb_token
  reg [15 : 0] arb_token;
  wire [15 : 0] arb_token$D_IN;
  wire arb_token$EN;

  // remaining internal signals
  wire [1 : 0] ab__h10277,
	       ab__h11517,
	       ab__h12708,
	       ab__h13850,
	       ab__h14943,
	       ab__h15987,
	       ab__h16982,
	       ab__h17928,
	       ab__h18825,
	       ab__h19673,
	       ab__h20472,
	       ab__h21222,
	       ab__h21923,
	       ab__h22575,
	       ab__h23178,
	       ab__h4638,
	       ab__h4653,
	       ab__h4668,
	       ab__h4683,
	       ab__h4698,
	       ab__h4713,
	       ab__h4728,
	       ab__h4743,
	       ab__h4758,
	       ab__h4773,
	       ab__h4788,
	       ab__h4803,
	       ab__h4818,
	       ab__h4833,
	       ab__h4848,
	       ab__h4863,
	       ab__h8983;
  wire NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d123,
       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d145,
       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d171,
       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d201,
       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d235,
       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d273,
       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d315,
       NOT_gen_grant_carry_0_BIT_1_23_38_AND_NOT_gen__ETC___d263,
       NOT_gen_grant_carry_0_BIT_1_23_38_AND_NOT_gen__ETC___d305,
       NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d181,
       NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d213,
       NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d249,
       NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d289,
       NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d143,
       NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d169,
       NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d199,
       NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d233,
       NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d271,
       NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d313,
       NOT_gen_grant_carry_2_BIT_1_59_76_AND_NOT_gen__ETC___d303,
       NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d211,
       NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d247,
       NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d287,
       NOT_gen_grant_carry_4_BIT_1_07_20_AND_NOT_gen__ETC___d245,
       NOT_gen_grant_carry_4_BIT_1_07_20_AND_NOT_gen__ETC___d285,
       NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d167,
       NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d197,
       NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d231,
       NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d269,
       NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d311,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d115,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d135,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d159,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d187,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d219,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d255,
       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d295,
       NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d133,
       NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d157,
       NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d185,
       NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d217,
       NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d253,
       NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d293,
       NOT_gen_grant_carry_6_BIT_1_41_56_AND_NOT_gen__ETC___d283,
       NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d195,
       NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d229,
       NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d267,
       NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d309,
       NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d155,
       NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d183,
       NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d215,
       NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d251,
       NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d291,
       NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d227,
       NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d265,
       NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d307,
       ab_BIT_0___h10969,
       ab_BIT_0___h12160,
       ab_BIT_0___h13302,
       ab_BIT_0___h14395,
       ab_BIT_0___h15439,
       ab_BIT_0___h16434,
       ab_BIT_0___h17380,
       ab_BIT_0___h18277,
       ab_BIT_0___h19125,
       ab_BIT_0___h19924,
       ab_BIT_0___h20674,
       ab_BIT_0___h21375,
       ab_BIT_0___h22027,
       ab_BIT_0___h22630,
       ab_BIT_0___h6251,
       ab_BIT_0___h6358,
       ab_BIT_0___h6465,
       ab_BIT_0___h6572,
       ab_BIT_0___h6679,
       ab_BIT_0___h6786,
       ab_BIT_0___h6893,
       ab_BIT_0___h7000,
       ab_BIT_0___h7107,
       ab_BIT_0___h7214,
       ab_BIT_0___h7321,
       ab_BIT_0___h7428,
       ab_BIT_0___h7535,
       ab_BIT_0___h7642,
       ab_BIT_0___h7749,
       ab_BIT_0___h9219,
       ab_BIT_0___h9729,
       arb_token_BIT_0___h6249,
       arb_token_BIT_10___h7319,
       arb_token_BIT_11___h7426,
       arb_token_BIT_12___h7533,
       arb_token_BIT_13___h7640,
       arb_token_BIT_14___h7747,
       arb_token_BIT_15___h7854,
       arb_token_BIT_1___h6356,
       arb_token_BIT_2___h6463,
       arb_token_BIT_3___h6570,
       arb_token_BIT_4___h6677,
       arb_token_BIT_5___h6784,
       arb_token_BIT_6___h6891,
       arb_token_BIT_7___h6998,
       arb_token_BIT_8___h7105,
       arb_token_BIT_9___h7212;

  // value method select
  assign select =
	     { ab__h4638[1] || ab__h8983[1],
	       !ab__h4638[1] && !ab__h8983[1] &&
	       (ab__h4653[1] || ab__h10277[1]),
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d115,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d123,
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d135,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d145,
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d159,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d171,
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d187,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d201,
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d219,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d235,
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d255,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d273,
	       NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d295,
	       !ab__h4638[1] && !ab__h8983[1] &&
	       NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d315 } ;

  // register arb_token
  assign arb_token$D_IN = { arb_token[0], arb_token[15:1] } ;
  assign arb_token$EN = EN_next ;

  // remaining internal signals
  module_gen_grant_carry instance_gen_grant_carry_31(.gen_grant_carry_c(1'd0),
						     .gen_grant_carry_r(select_requests[0]),
						     .gen_grant_carry_p(arb_token_BIT_0___h6249),
						     .gen_grant_carry(ab__h4863));
  module_gen_grant_carry instance_gen_grant_carry_1(.gen_grant_carry_c(ab_BIT_0___h6251),
						    .gen_grant_carry_r(select_requests[1]),
						    .gen_grant_carry_p(arb_token_BIT_1___h6356),
						    .gen_grant_carry(ab__h4848));
  module_gen_grant_carry instance_gen_grant_carry_0(.gen_grant_carry_c(ab_BIT_0___h6358),
						    .gen_grant_carry_r(select_requests[2]),
						    .gen_grant_carry_p(arb_token_BIT_2___h6463),
						    .gen_grant_carry(ab__h4833));
  module_gen_grant_carry instance_gen_grant_carry_2(.gen_grant_carry_c(ab_BIT_0___h6465),
						    .gen_grant_carry_r(select_requests[3]),
						    .gen_grant_carry_p(arb_token_BIT_3___h6570),
						    .gen_grant_carry(ab__h4818));
  module_gen_grant_carry instance_gen_grant_carry_3(.gen_grant_carry_c(ab_BIT_0___h6572),
						    .gen_grant_carry_r(select_requests[4]),
						    .gen_grant_carry_p(arb_token_BIT_4___h6677),
						    .gen_grant_carry(ab__h4803));
  module_gen_grant_carry instance_gen_grant_carry_4(.gen_grant_carry_c(ab_BIT_0___h6679),
						    .gen_grant_carry_r(select_requests[5]),
						    .gen_grant_carry_p(arb_token_BIT_5___h6784),
						    .gen_grant_carry(ab__h4788));
  module_gen_grant_carry instance_gen_grant_carry_5(.gen_grant_carry_c(ab_BIT_0___h6786),
						    .gen_grant_carry_r(select_requests[6]),
						    .gen_grant_carry_p(arb_token_BIT_6___h6891),
						    .gen_grant_carry(ab__h4773));
  module_gen_grant_carry instance_gen_grant_carry_6(.gen_grant_carry_c(ab_BIT_0___h6893),
						    .gen_grant_carry_r(select_requests[7]),
						    .gen_grant_carry_p(arb_token_BIT_7___h6998),
						    .gen_grant_carry(ab__h4758));
  module_gen_grant_carry instance_gen_grant_carry_7(.gen_grant_carry_c(ab_BIT_0___h7000),
						    .gen_grant_carry_r(select_requests[8]),
						    .gen_grant_carry_p(arb_token_BIT_8___h7105),
						    .gen_grant_carry(ab__h4743));
  module_gen_grant_carry instance_gen_grant_carry_8(.gen_grant_carry_c(ab_BIT_0___h7107),
						    .gen_grant_carry_r(select_requests[9]),
						    .gen_grant_carry_p(arb_token_BIT_9___h7212),
						    .gen_grant_carry(ab__h4728));
  module_gen_grant_carry instance_gen_grant_carry_9(.gen_grant_carry_c(ab_BIT_0___h7214),
						    .gen_grant_carry_r(select_requests[10]),
						    .gen_grant_carry_p(arb_token_BIT_10___h7319),
						    .gen_grant_carry(ab__h4713));
  module_gen_grant_carry instance_gen_grant_carry_10(.gen_grant_carry_c(ab_BIT_0___h7321),
						     .gen_grant_carry_r(select_requests[11]),
						     .gen_grant_carry_p(arb_token_BIT_11___h7426),
						     .gen_grant_carry(ab__h4698));
  module_gen_grant_carry instance_gen_grant_carry_11(.gen_grant_carry_c(ab_BIT_0___h7428),
						     .gen_grant_carry_r(select_requests[12]),
						     .gen_grant_carry_p(arb_token_BIT_12___h7533),
						     .gen_grant_carry(ab__h4683));
  module_gen_grant_carry instance_gen_grant_carry_12(.gen_grant_carry_c(ab_BIT_0___h7535),
						     .gen_grant_carry_r(select_requests[13]),
						     .gen_grant_carry_p(arb_token_BIT_13___h7640),
						     .gen_grant_carry(ab__h4668));
  module_gen_grant_carry instance_gen_grant_carry_13(.gen_grant_carry_c(ab_BIT_0___h7642),
						     .gen_grant_carry_r(select_requests[14]),
						     .gen_grant_carry_p(arb_token_BIT_14___h7747),
						     .gen_grant_carry(ab__h4653));
  module_gen_grant_carry instance_gen_grant_carry_14(.gen_grant_carry_c(ab_BIT_0___h7749),
						     .gen_grant_carry_r(select_requests[15]),
						     .gen_grant_carry_p(arb_token_BIT_15___h7854),
						     .gen_grant_carry(ab__h4638));
  module_gen_grant_carry instance_gen_grant_carry_15(.gen_grant_carry_c(ab_BIT_0___h9219),
						     .gen_grant_carry_r(select_requests[0]),
						     .gen_grant_carry_p(arb_token_BIT_0___h6249),
						     .gen_grant_carry(ab__h23178));
  module_gen_grant_carry instance_gen_grant_carry_16(.gen_grant_carry_c(ab_BIT_0___h22630),
						     .gen_grant_carry_r(select_requests[1]),
						     .gen_grant_carry_p(arb_token_BIT_1___h6356),
						     .gen_grant_carry(ab__h22575));
  module_gen_grant_carry instance_gen_grant_carry_17(.gen_grant_carry_c(ab_BIT_0___h22027),
						     .gen_grant_carry_r(select_requests[2]),
						     .gen_grant_carry_p(arb_token_BIT_2___h6463),
						     .gen_grant_carry(ab__h21923));
  module_gen_grant_carry instance_gen_grant_carry_18(.gen_grant_carry_c(ab_BIT_0___h21375),
						     .gen_grant_carry_r(select_requests[3]),
						     .gen_grant_carry_p(arb_token_BIT_3___h6570),
						     .gen_grant_carry(ab__h21222));
  module_gen_grant_carry instance_gen_grant_carry_19(.gen_grant_carry_c(ab_BIT_0___h20674),
						     .gen_grant_carry_r(select_requests[4]),
						     .gen_grant_carry_p(arb_token_BIT_4___h6677),
						     .gen_grant_carry(ab__h20472));
  module_gen_grant_carry instance_gen_grant_carry_20(.gen_grant_carry_c(ab_BIT_0___h19924),
						     .gen_grant_carry_r(select_requests[5]),
						     .gen_grant_carry_p(arb_token_BIT_5___h6784),
						     .gen_grant_carry(ab__h19673));
  module_gen_grant_carry instance_gen_grant_carry_21(.gen_grant_carry_c(ab_BIT_0___h19125),
						     .gen_grant_carry_r(select_requests[6]),
						     .gen_grant_carry_p(arb_token_BIT_6___h6891),
						     .gen_grant_carry(ab__h18825));
  module_gen_grant_carry instance_gen_grant_carry_22(.gen_grant_carry_c(ab_BIT_0___h18277),
						     .gen_grant_carry_r(select_requests[7]),
						     .gen_grant_carry_p(arb_token_BIT_7___h6998),
						     .gen_grant_carry(ab__h17928));
  module_gen_grant_carry instance_gen_grant_carry_23(.gen_grant_carry_c(ab_BIT_0___h17380),
						     .gen_grant_carry_r(select_requests[8]),
						     .gen_grant_carry_p(arb_token_BIT_8___h7105),
						     .gen_grant_carry(ab__h16982));
  module_gen_grant_carry instance_gen_grant_carry_24(.gen_grant_carry_c(ab_BIT_0___h16434),
						     .gen_grant_carry_r(select_requests[9]),
						     .gen_grant_carry_p(arb_token_BIT_9___h7212),
						     .gen_grant_carry(ab__h15987));
  module_gen_grant_carry instance_gen_grant_carry_25(.gen_grant_carry_c(ab_BIT_0___h15439),
						     .gen_grant_carry_r(select_requests[10]),
						     .gen_grant_carry_p(arb_token_BIT_10___h7319),
						     .gen_grant_carry(ab__h14943));
  module_gen_grant_carry instance_gen_grant_carry_26(.gen_grant_carry_c(ab_BIT_0___h14395),
						     .gen_grant_carry_r(select_requests[11]),
						     .gen_grant_carry_p(arb_token_BIT_11___h7426),
						     .gen_grant_carry(ab__h13850));
  module_gen_grant_carry instance_gen_grant_carry_27(.gen_grant_carry_c(ab_BIT_0___h13302),
						     .gen_grant_carry_r(select_requests[12]),
						     .gen_grant_carry_p(arb_token_BIT_12___h7533),
						     .gen_grant_carry(ab__h12708));
  module_gen_grant_carry instance_gen_grant_carry_28(.gen_grant_carry_c(ab_BIT_0___h12160),
						     .gen_grant_carry_r(select_requests[13]),
						     .gen_grant_carry_p(arb_token_BIT_13___h7640),
						     .gen_grant_carry(ab__h11517));
  module_gen_grant_carry instance_gen_grant_carry_29(.gen_grant_carry_c(ab_BIT_0___h10969),
						     .gen_grant_carry_r(select_requests[14]),
						     .gen_grant_carry_p(arb_token_BIT_14___h7747),
						     .gen_grant_carry(ab__h10277));
  module_gen_grant_carry instance_gen_grant_carry_30(.gen_grant_carry_c(ab_BIT_0___h9729),
						     .gen_grant_carry_r(select_requests[15]),
						     .gen_grant_carry_p(arb_token_BIT_15___h7854),
						     .gen_grant_carry(ab__h8983));
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d123 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     (ab__h4683[1] || ab__h12708[1]) ;
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d145 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d143 ;
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d171 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d169 ;
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d201 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d199 ;
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d235 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d233 ;
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d273 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d271 ;
  assign NOT_gen_grant_carry_0_BIT_1_03_08_AND_NOT_gen__ETC___d315 =
	     !ab__h4653[1] && !ab__h10277[1] && !ab__h4668[1] &&
	     !ab__h11517[1] &&
	     NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d313 ;
  assign NOT_gen_grant_carry_0_BIT_1_23_38_AND_NOT_gen__ETC___d263 =
	     !ab__h4803[1] && !ab__h20472[1] && !ab__h4818[1] &&
	     !ab__h21222[1] &&
	     (ab__h4833[1] || ab__h21923[1]) ;
  assign NOT_gen_grant_carry_0_BIT_1_23_38_AND_NOT_gen__ETC___d305 =
	     !ab__h4803[1] && !ab__h20472[1] && !ab__h4818[1] &&
	     !ab__h21222[1] &&
	     NOT_gen_grant_carry_2_BIT_1_59_76_AND_NOT_gen__ETC___d303 ;
  assign NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d181 =
	     !ab__h4728[1] && !ab__h15987[1] && !ab__h4743[1] &&
	     !ab__h16982[1] &&
	     (ab__h4758[1] || ab__h17928[1]) ;
  assign NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d213 =
	     !ab__h4728[1] && !ab__h15987[1] && !ab__h4743[1] &&
	     !ab__h16982[1] &&
	     NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d211 ;
  assign NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d249 =
	     !ab__h4728[1] && !ab__h15987[1] && !ab__h4743[1] &&
	     !ab__h16982[1] &&
	     NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d247 ;
  assign NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d289 =
	     !ab__h4728[1] && !ab__h15987[1] && !ab__h4743[1] &&
	     !ab__h16982[1] &&
	     NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d287 ;
  assign NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d143 =
	     !ab__h4683[1] && !ab__h12708[1] && !ab__h4698[1] &&
	     !ab__h13850[1] &&
	     (ab__h4713[1] || ab__h14943[1]) ;
  assign NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d169 =
	     !ab__h4683[1] && !ab__h12708[1] && !ab__h4698[1] &&
	     !ab__h13850[1] &&
	     NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d167 ;
  assign NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d199 =
	     !ab__h4683[1] && !ab__h12708[1] && !ab__h4698[1] &&
	     !ab__h13850[1] &&
	     NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d197 ;
  assign NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d233 =
	     !ab__h4683[1] && !ab__h12708[1] && !ab__h4698[1] &&
	     !ab__h13850[1] &&
	     NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d231 ;
  assign NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d271 =
	     !ab__h4683[1] && !ab__h12708[1] && !ab__h4698[1] &&
	     !ab__h13850[1] &&
	     NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d269 ;
  assign NOT_gen_grant_carry_2_BIT_1_19_26_AND_NOT_gen__ETC___d313 =
	     !ab__h4683[1] && !ab__h12708[1] && !ab__h4698[1] &&
	     !ab__h13850[1] &&
	     NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d311 ;
  assign NOT_gen_grant_carry_2_BIT_1_59_76_AND_NOT_gen__ETC___d303 =
	     !ab__h4833[1] && !ab__h21923[1] && !ab__h4848[1] &&
	     !ab__h22575[1] &&
	     (ab__h4863[1] || ab__h23178[1]) ;
  assign NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d211 =
	     !ab__h4758[1] && !ab__h17928[1] && !ab__h4773[1] &&
	     !ab__h18825[1] &&
	     (ab__h4788[1] || ab__h19673[1]) ;
  assign NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d247 =
	     !ab__h4758[1] && !ab__h17928[1] && !ab__h4773[1] &&
	     !ab__h18825[1] &&
	     NOT_gen_grant_carry_4_BIT_1_07_20_AND_NOT_gen__ETC___d245 ;
  assign NOT_gen_grant_carry_2_BIT_1_77_88_AND_NOT_gen__ETC___d287 =
	     !ab__h4758[1] && !ab__h17928[1] && !ab__h4773[1] &&
	     !ab__h18825[1] &&
	     NOT_gen_grant_carry_4_BIT_1_07_20_AND_NOT_gen__ETC___d285 ;
  assign NOT_gen_grant_carry_4_BIT_1_07_20_AND_NOT_gen__ETC___d245 =
	     !ab__h4788[1] && !ab__h19673[1] && !ab__h4803[1] &&
	     !ab__h20472[1] &&
	     (ab__h4818[1] || ab__h21222[1]) ;
  assign NOT_gen_grant_carry_4_BIT_1_07_20_AND_NOT_gen__ETC___d285 =
	     !ab__h4788[1] && !ab__h19673[1] && !ab__h4803[1] &&
	     !ab__h20472[1] &&
	     NOT_gen_grant_carry_6_BIT_1_41_56_AND_NOT_gen__ETC___d283 ;
  assign NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d167 =
	     !ab__h4713[1] && !ab__h14943[1] && !ab__h4728[1] &&
	     !ab__h15987[1] &&
	     (ab__h4743[1] || ab__h16982[1]) ;
  assign NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d197 =
	     !ab__h4713[1] && !ab__h14943[1] && !ab__h4728[1] &&
	     !ab__h15987[1] &&
	     NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d195 ;
  assign NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d231 =
	     !ab__h4713[1] && !ab__h14943[1] && !ab__h4728[1] &&
	     !ab__h15987[1] &&
	     NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d229 ;
  assign NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d269 =
	     !ab__h4713[1] && !ab__h14943[1] && !ab__h4728[1] &&
	     !ab__h15987[1] &&
	     NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d267 ;
  assign NOT_gen_grant_carry_4_BIT_1_39_48_AND_NOT_gen__ETC___d311 =
	     !ab__h4713[1] && !ab__h14943[1] && !ab__h4728[1] &&
	     !ab__h15987[1] &&
	     NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d309 ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d115 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     (ab__h4668[1] || ab__h11517[1]) ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d135 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d133 ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d159 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d157 ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d187 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d185 ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d219 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d217 ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d255 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d253 ;
  assign NOT_gen_grant_carry_4_BIT_1_5_00_AND_NOT_gen_g_ETC___d295 =
	     !ab__h4638[1] && !ab__h8983[1] && !ab__h4653[1] &&
	     !ab__h10277[1] &&
	     NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d293 ;
  assign NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d133 =
	     !ab__h4668[1] && !ab__h11517[1] && !ab__h4683[1] &&
	     !ab__h12708[1] &&
	     (ab__h4698[1] || ab__h13850[1]) ;
  assign NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d157 =
	     !ab__h4668[1] && !ab__h11517[1] && !ab__h4683[1] &&
	     !ab__h12708[1] &&
	     NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d155 ;
  assign NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d185 =
	     !ab__h4668[1] && !ab__h11517[1] && !ab__h4683[1] &&
	     !ab__h12708[1] &&
	     NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d183 ;
  assign NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d217 =
	     !ab__h4668[1] && !ab__h11517[1] && !ab__h4683[1] &&
	     !ab__h12708[1] &&
	     NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d215 ;
  assign NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d253 =
	     !ab__h4668[1] && !ab__h11517[1] && !ab__h4683[1] &&
	     !ab__h12708[1] &&
	     NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d251 ;
  assign NOT_gen_grant_carry_6_BIT_1_11_16_AND_NOT_gen__ETC___d293 =
	     !ab__h4668[1] && !ab__h11517[1] && !ab__h4683[1] &&
	     !ab__h12708[1] &&
	     NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d291 ;
  assign NOT_gen_grant_carry_6_BIT_1_41_56_AND_NOT_gen__ETC___d283 =
	     !ab__h4818[1] && !ab__h21222[1] && !ab__h4833[1] &&
	     !ab__h21923[1] &&
	     (ab__h4848[1] || ab__h22575[1]) ;
  assign NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d195 =
	     !ab__h4743[1] && !ab__h16982[1] && !ab__h4758[1] &&
	     !ab__h17928[1] &&
	     (ab__h4773[1] || ab__h18825[1]) ;
  assign NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d229 =
	     !ab__h4743[1] && !ab__h16982[1] && !ab__h4758[1] &&
	     !ab__h17928[1] &&
	     NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d227 ;
  assign NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d267 =
	     !ab__h4743[1] && !ab__h16982[1] && !ab__h4758[1] &&
	     !ab__h17928[1] &&
	     NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d265 ;
  assign NOT_gen_grant_carry_6_BIT_1_63_74_AND_NOT_gen__ETC___d309 =
	     !ab__h4743[1] && !ab__h16982[1] && !ab__h4758[1] &&
	     !ab__h17928[1] &&
	     NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d307 ;
  assign NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d155 =
	     !ab__h4698[1] && !ab__h13850[1] && !ab__h4713[1] &&
	     !ab__h14943[1] &&
	     (ab__h4728[1] || ab__h15987[1]) ;
  assign NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d183 =
	     !ab__h4698[1] && !ab__h13850[1] && !ab__h4713[1] &&
	     !ab__h14943[1] &&
	     NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d181 ;
  assign NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d215 =
	     !ab__h4698[1] && !ab__h13850[1] && !ab__h4713[1] &&
	     !ab__h14943[1] &&
	     NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d213 ;
  assign NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d251 =
	     !ab__h4698[1] && !ab__h13850[1] && !ab__h4713[1] &&
	     !ab__h14943[1] &&
	     NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d249 ;
  assign NOT_gen_grant_carry_8_BIT_1_29_36_AND_NOT_gen__ETC___d291 =
	     !ab__h4698[1] && !ab__h13850[1] && !ab__h4713[1] &&
	     !ab__h14943[1] &&
	     NOT_gen_grant_carry_0_BIT_1_51_60_AND_NOT_gen__ETC___d289 ;
  assign NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d227 =
	     !ab__h4773[1] && !ab__h18825[1] && !ab__h4788[1] &&
	     !ab__h19673[1] &&
	     (ab__h4803[1] || ab__h20472[1]) ;
  assign NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d265 =
	     !ab__h4773[1] && !ab__h18825[1] && !ab__h4788[1] &&
	     !ab__h19673[1] &&
	     NOT_gen_grant_carry_0_BIT_1_23_38_AND_NOT_gen__ETC___d263 ;
  assign NOT_gen_grant_carry_8_BIT_1_91_04_AND_NOT_gen__ETC___d307 =
	     !ab__h4773[1] && !ab__h18825[1] && !ab__h4788[1] &&
	     !ab__h19673[1] &&
	     NOT_gen_grant_carry_0_BIT_1_23_38_AND_NOT_gen__ETC___d305 ;
  assign ab_BIT_0___h10969 = ab__h11517[0] ;
  assign ab_BIT_0___h12160 = ab__h12708[0] ;
  assign ab_BIT_0___h13302 = ab__h13850[0] ;
  assign ab_BIT_0___h14395 = ab__h14943[0] ;
  assign ab_BIT_0___h15439 = ab__h15987[0] ;
  assign ab_BIT_0___h16434 = ab__h16982[0] ;
  assign ab_BIT_0___h17380 = ab__h17928[0] ;
  assign ab_BIT_0___h18277 = ab__h18825[0] ;
  assign ab_BIT_0___h19125 = ab__h19673[0] ;
  assign ab_BIT_0___h19924 = ab__h20472[0] ;
  assign ab_BIT_0___h20674 = ab__h21222[0] ;
  assign ab_BIT_0___h21375 = ab__h21923[0] ;
  assign ab_BIT_0___h22027 = ab__h22575[0] ;
  assign ab_BIT_0___h22630 = ab__h23178[0] ;
  assign ab_BIT_0___h6251 = ab__h4863[0] ;
  assign ab_BIT_0___h6358 = ab__h4848[0] ;
  assign ab_BIT_0___h6465 = ab__h4833[0] ;
  assign ab_BIT_0___h6572 = ab__h4818[0] ;
  assign ab_BIT_0___h6679 = ab__h4803[0] ;
  assign ab_BIT_0___h6786 = ab__h4788[0] ;
  assign ab_BIT_0___h6893 = ab__h4773[0] ;
  assign ab_BIT_0___h7000 = ab__h4758[0] ;
  assign ab_BIT_0___h7107 = ab__h4743[0] ;
  assign ab_BIT_0___h7214 = ab__h4728[0] ;
  assign ab_BIT_0___h7321 = ab__h4713[0] ;
  assign ab_BIT_0___h7428 = ab__h4698[0] ;
  assign ab_BIT_0___h7535 = ab__h4683[0] ;
  assign ab_BIT_0___h7642 = ab__h4668[0] ;
  assign ab_BIT_0___h7749 = ab__h4653[0] ;
  assign ab_BIT_0___h9219 = ab__h4638[0] ;
  assign ab_BIT_0___h9729 = ab__h10277[0] ;
  assign arb_token_BIT_0___h6249 = arb_token[0] ;
  assign arb_token_BIT_10___h7319 = arb_token[10] ;
  assign arb_token_BIT_11___h7426 = arb_token[11] ;
  assign arb_token_BIT_12___h7533 = arb_token[12] ;
  assign arb_token_BIT_13___h7640 = arb_token[13] ;
  assign arb_token_BIT_14___h7747 = arb_token[14] ;
  assign arb_token_BIT_15___h7854 = arb_token[15] ;
  assign arb_token_BIT_1___h6356 = arb_token[1] ;
  assign arb_token_BIT_2___h6463 = arb_token[2] ;
  assign arb_token_BIT_3___h6570 = arb_token[3] ;
  assign arb_token_BIT_4___h6677 = arb_token[4] ;
  assign arb_token_BIT_5___h6784 = arb_token[5] ;
  assign arb_token_BIT_6___h6891 = arb_token[6] ;
  assign arb_token_BIT_7___h6998 = arb_token[7] ;
  assign arb_token_BIT_8___h7105 = arb_token[8] ;
  assign arb_token_BIT_9___h7212 = arb_token[9] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (!RST_N)
      begin
        arb_token <= `BSV_ASSIGNMENT_DELAY 16'd1;
      end
    else
      begin
        if (arb_token$EN) arb_token <= `BSV_ASSIGNMENT_DELAY arb_token$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    arb_token = 16'hAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkOutputArbiter

