/*
 * These source files contain a hardware description of a network
 * automatically generated by CONNECT (CONfigurable NEtwork Creation Tool).
 *
 * This product includes a hardware design developed by Carnegie Mellon
 * University.
 *
 * Copyright (c) 2012 by Michael K. Papamichael, Carnegie Mellon University
 *
 * For more information, see the CONNECT project website at:
 *   http://www.ece.cmu.edu/~mpapamic/connect
 *
 * This design is provided for internal, non-commercial research use only, 
 * cannot be used for, or in support of, goods or services, and is not for
 * redistribution, with or without modifications.
 * 
 * You may not use the name "Carnegie Mellon University" or derivations
 * thereof to endorse or promote products derived from this software.
 *
 * THE SOFTWARE IS PROVIDED "AS-IS" WITHOUT ANY WARRANTY OF ANY KIND, EITHER
 * EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO ANY WARRANTY
 * THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS OR BE ERROR-FREE AND ANY
 * IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
 * TITLE, OR NON-INFRINGEMENT.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
 * BE LIABLE FOR ANY DAMAGES, INCLUDING BUT NOT LIMITED TO DIRECT, INDIRECT,
 * SPECIAL OR CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM, OR IN
 * ANY WAY CONNECTED WITH THIS SOFTWARE (WHETHER OR NOT BASED UPON WARRANTY,
 * CONTRACT, TORT OR OTHERWISE).
 *
 */


//
// Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
//
// On Sun Jun 10 13:13:00 EDT 2018
//
// Method conflict info:
// Method: outport_encoder
// Conflict-free: outport_encoder
//
//
// Ports:
// Name                         I/O  size props
// outport_encoder                O     5
// outport_encoder_vec            I    16
//
// Combinational paths from inputs to outputs:
//   outport_encoder_vec -> outport_encoder
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
`define BSV_ASSIGNMENT_DELAY
`endif

module module_outport_encoder(outport_encoder_vec,
			      outport_encoder);
  // value method outport_encoder
  input  [15 : 0] outport_encoder_vec;
  output [4 : 0] outport_encoder;

  // signals for module outputs
  wire [4 : 0] outport_encoder;

  // value method outport_encoder
  assign outport_encoder =
	     { outport_encoder_vec[0] || outport_encoder_vec[1] ||
	       outport_encoder_vec[2] ||
	       outport_encoder_vec[3] ||
	       outport_encoder_vec[4] ||
	       outport_encoder_vec[5] ||
	       outport_encoder_vec[6] ||
	       outport_encoder_vec[7] ||
	       outport_encoder_vec[8] ||
	       outport_encoder_vec[9] ||
	       outport_encoder_vec[10] ||
	       outport_encoder_vec[11] ||
	       outport_encoder_vec[12] ||
	       outport_encoder_vec[13] ||
	       outport_encoder_vec[14] ||
	       outport_encoder_vec[15],
	       outport_encoder_vec[0] ?
		 4'd0 :
		 (outport_encoder_vec[1] ?
		    4'd1 :
		    (outport_encoder_vec[2] ?
		       4'd2 :
		       (outport_encoder_vec[3] ?
			  4'd3 :
			  (outport_encoder_vec[4] ?
			     4'd4 :
			     (outport_encoder_vec[5] ?
				4'd5 :
				(outport_encoder_vec[6] ?
				   4'd6 :
				   (outport_encoder_vec[7] ?
				      4'd7 :
				      (outport_encoder_vec[8] ?
					 4'd8 :
					 (outport_encoder_vec[9] ?
					    4'd9 :
					    (outport_encoder_vec[10] ?
					       4'd10 :
					       (outport_encoder_vec[11] ?
						  4'd11 :
						  (outport_encoder_vec[12] ?
						     4'd12 :
						     (outport_encoder_vec[13] ?
							4'd13 :
							(outport_encoder_vec[14] ?
							   4'd14 :
							   4'd15)))))))))))))) } ;
endmodule  // module_outport_encoder

