# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/VivadoIPs/myFifo/myFifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myFifo || ORIG_REF_NAME==myFifo} -quiet] -quiet
