# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/App/Vivado/openNoc.cache/wt [current_project]
set_property parent.project_path C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/App/Vivado/openNoc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/App/Vivado/openNoc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/rtl/include_file.v
set_property file_type "Verilog Header" [get_files C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/rtl/include_file.v]
read_verilog -library xil_defaultlib {
  C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/rtl/nbyn_pe.v
  C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/rtl/nbyn_pe_2.v
  C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/rtl/nbyn_scheduler.v
  C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/rtl/procTop.v
}
read_ip -quiet C:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/VivadoIPs/myFifo/myFifo.xci
set_property used_in_implementation false [get_files -all c:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/VivadoIPs/myFifo/myFifo_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/vipin.kizheppatt/OneDrive/Reserch/mygit/OpenNoc/src/Verilog/VivadoIPs/myFifo/myFifo/myFifo.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top procTop -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef procTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file procTop_utilization_synth.rpt -pb procTop_utilization_synth.pb"
